CREATE DATABASE tpch;
USE tpch;

CREATE DATABASE IF NOT EXISTS tpch;
USE tpch;

CREATE TABLE NATION (
    N_NATIONKEY INTEGER NOT NULL,
    N_NAME CHAR(25) NOT NULL,
    N_REGIONKEY INTEGER NOT NULL,
    N_COMMENT VARCHAR(152),
    PRIMARY KEY (N_NATIONKEY)
);

CREATE TABLE REGION (
    R_REGIONKEY INTEGER NOT NULL,
    R_NAME CHAR(25) NOT NULL,
    R_COMMENT VARCHAR(152),
    PRIMARY KEY (R_REGIONKEY)
);

CREATE TABLE PART (
    P_PARTKEY INTEGER NOT NULL,
    P_NAME VARCHAR(55) NOT NULL,
    P_MFGR CHAR(25) NOT NULL,
    P_BRAND CHAR(10) NOT NULL,
    P_TYPE VARCHAR(25) NOT NULL,
    P_SIZE INTEGER NOT NULL,
    P_CONTAINER CHAR(10) NOT NULL,
    P_RETAILPRICE DECIMAL(15,2) NOT NULL,
    P_COMMENT VARCHAR(23) NOT NULL,
    PRIMARY KEY (P_PARTKEY)
);

CREATE TABLE SUPPLIER (
    S_SUPPKEY INTEGER NOT NULL,
    S_NAME CHAR(25) NOT NULL,
    S_ADDRESS VARCHAR(40) NOT NULL,
    S_NATIONKEY INTEGER NOT NULL,
    S_PHONE CHAR(15) NOT NULL,
    S_ACCTBAL DECIMAL(15,2) NOT NULL,
    S_COMMENT VARCHAR(101) NOT NULL,
    PRIMARY KEY (S_SUPPKEY)
);

CREATE TABLE PARTSUPP (
    PS_PARTKEY INTEGER NOT NULL,
    PS_SUPPKEY INTEGER NOT NULL,
    PS_AVAILQTY INTEGER NOT NULL,
    PS_SUPPLYCOST DECIMAL(15,2) NOT NULL,
    PS_COMMENT VARCHAR(199) NOT NULL,
    PRIMARY KEY (PS_PARTKEY, PS_SUPPKEY)
);

CREATE TABLE CUSTOMER (
    C_CUSTKEY INTEGER NOT NULL,
    C_NAME VARCHAR(25) NOT NULL,
    C_ADDRESS VARCHAR(40) NOT NULL,
    C_NATIONKEY INTEGER NOT NULL,
    C_PHONE CHAR(15) NOT NULL,
    C_ACCTBAL DECIMAL(15,2) NOT NULL,
    C_MKTSEGMENT CHAR(10) NOT NULL,
    C_COMMENT VARCHAR(117) NOT NULL,
    PRIMARY KEY (C_CUSTKEY)
);

CREATE TABLE ORDERS (
    O_ORDERKEY INTEGER NOT NULL,
    O_CUSTKEY INTEGER NOT NULL,
    O_ORDERSTATUS CHAR(1) NOT NULL,
    O_TOTALPRICE DECIMAL(15,2) NOT NULL,
    O_ORDERDATE DATE NOT NULL,
    O_ORDERPRIORITY CHAR(15) NOT NULL,
    O_CLERK CHAR(15) NOT NULL,
    O_SHIPPRIORITY INTEGER NOT NULL,
    O_COMMENT VARCHAR(79) NOT NULL,
    PRIMARY KEY (O_ORDERKEY)
);

CREATE TABLE LINEITEM (
    L_ORDERKEY INTEGER NOT NULL,
    L_PARTKEY INTEGER NOT NULL,
    L_SUPPKEY INTEGER NOT NULL,
    L_LINENUMBER INTEGER NOT NULL,
    L_QUANTITY DECIMAL(15,2) NOT NULL,
    L_EXTENDEDPRICE DECIMAL(15,2) NOT NULL,
    L_DISCOUNT DECIMAL(15,2) NOT NULL,
    L_TAX DECIMAL(15,2) NOT NULL,
    L_RETURNFLAG CHAR(1) NOT NULL,
    L_LINESTATUS CHAR(1) NOT NULL,
    L_SHIPDATE DATE NOT NULL,
    L_COMMITDATE DATE NOT NULL,
    L_RECEIPTDATE DATE NOT NULL,
    L_SHIPINSTRUCT CHAR(25) NOT NULL,
    L_SHIPMODE CHAR(10) NOT NULL,
    L_COMMENT VARCHAR(44) NOT NULL,
    PRIMARY KEY (L_ORDERKEY, L_LINENUMBER)
);

SET GLOBAL local_infile = 1;

SHOW VARIABLES LIKE 'local_infile';
SHOW VARIABLES LIKE 'secure_file_priv';

LOAD DATA LOCAL INFILE '/Users/sayememon/Downloads/tpch/dbgen/region.tbl'
INTO TABLE REGION
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
(R_REGIONKEY, R_NAME, R_COMMENT);

LOAD DATA LOCAL INFILE '/Users/sayememon/Downloads/tpch/dbgen/nation.tbl'
INTO TABLE NATION
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
(N_NATIONKEY, N_NAME, N_REGIONKEY, N_COMMENT);

LOAD DATA LOCAL INFILE '/Users/sayememon/Downloads/tpch/dbgen/part.tbl'
INTO TABLE PART
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
(P_PARTKEY, P_NAME, P_MFGR, P_BRAND, P_TYPE, P_SIZE, P_CONTAINER, P_RETAILPRICE, P_COMMENT);

LOAD DATA LOCAL INFILE '/Users/sayememon/Downloads/tpch/dbgen/supplier.tbl'
INTO TABLE SUPPLIER
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
(S_SUPPKEY, S_NAME, S_ADDRESS, S_NATIONKEY, S_PHONE, S_ACCTBAL, S_COMMENT);

LOAD DATA LOCAL INFILE '/Users/sayememon/Downloads/tpch/dbgen/customer.tbl'
INTO TABLE CUSTOMER
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
(C_CUSTKEY, C_NAME, C_ADDRESS, C_NATIONKEY, C_PHONE, C_ACCTBAL, C_MKTSEGMENT, C_COMMENT);

LOAD DATA LOCAL INFILE '/Users/sayememon/Downloads/tpch/dbgen/orders.tbl'
INTO TABLE ORDERS
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
(O_ORDERKEY, O_CUSTKEY, O_ORDERSTATUS, O_TOTALPRICE, O_ORDERDATE, O_ORDERPRIORITY, O_CLERK, O_SHIPPRIORITY, O_COMMENT);

LOAD DATA LOCAL INFILE '/Users/sayememon/Downloads/tpch/dbgen/partsupp.tbl'
INTO TABLE PARTSUPP
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
(PS_PARTKEY, PS_SUPPKEY, PS_AVAILQTY, PS_SUPPLYCOST, PS_COMMENT);

LOAD DATA LOCAL INFILE '/Users/sayememon/Downloads/tpch/dbgen/lineitem.tbl'
INTO TABLE LINEITEM
FIELDS TERMINATED BY '|'
LINES TERMINATED BY '\n'
(L_ORDERKEY, L_PARTKEY, L_SUPPKEY, L_LINENUMBER, L_QUANTITY, L_EXTENDEDPRICE, L_DISCOUNT, L_TAX, L_RETURNFLAG, L_LINESTATUS, L_SHIPDATE, L_COMMITDATE, L_RECEIPTDATE, L_SHIPINSTRUCT, L_SHIPMODE, L_COMMENT);

SELECT COUNT(*) AS region_rows FROM REGION;
SELECT COUNT(*) AS nation_rows FROM NATION;
SELECT COUNT(*) AS customer_rows FROM CUSTOMER;
SELECT COUNT(*) AS orders_rows FROM ORDERS;
SELECT COUNT(*) AS lineitem_rows FROM LINEITEM;

USE tpch;

SELECT COUNT(*) AS region_rows FROM REGION;
SELECT COUNT(*) AS nation_rows FROM NATION;
SELECT COUNT(*) AS part_rows FROM PART;
SELECT COUNT(*) AS supplier_rows FROM SUPPLIER;
SELECT COUNT(*) AS partsupp_rows FROM PARTSUPP;
SELECT COUNT(*) AS customer_rows FROM CUSTOMER;
SELECT COUNT(*) AS orders_rows FROM ORDERS;
SELECT COUNT(*) AS lineitem_rows FROM LINEITEM;

USE tpch;

SELECT *
FROM ORDERS
WHERE O_CUSTKEY = 100;

SELECT *
FROM LINEITEM
WHERE L_PARTKEY = 500;

SELECT *
FROM CUSTOMER
WHERE C_NATIONKEY = 10;

SELECT *
FROM ORDERS
WHERE O_ORDERDATE >= '1995-01-01';


EXPLAIN SELECT *
FROM ORDERS
WHERE O_CUSTKEY = 100;

CREATE INDEX idx_orders_custkey
ON ORDERS(O_CUSTKEY);

EXPLAIN
SELECT *
FROM ORDERS
WHERE O_CUSTKEY = 100;

EXPLAIN SELECT * FROM LINEITEM WHERE L_PARTKEY = 500;
EXPLAIN SELECT * FROM CUSTOMER WHERE C_NATIONKEY = 10;
EXPLAIN SELECT * FROM ORDERS WHERE O_ORDERDATE = '1995-03-15';
EXPLAIN SELECT * FROM PARTSUPP WHERE PS_PARTKEY = 100;

CREATE INDEX idx_lineitem_partkey ON LINEITEM(L_PARTKEY);
CREATE INDEX idx_customer_nationkey ON CUSTOMER(C_NATIONKEY);
CREATE INDEX idx_orders_orderdate ON ORDERS(O_ORDERDATE);
CREATE INDEX idx_partsupp_partkey ON PARTSUPP(PS_PARTKEY);

EXPLAIN SELECT * FROM LINEITEM WHERE L_PARTKEY = 500;
EXPLAIN SELECT * FROM CUSTOMER WHERE C_NATIONKEY = 10;
EXPLAIN SELECT * FROM ORDERS WHERE O_ORDERDATE = '1995-03-15';
EXPLAIN SELECT * FROM PARTSUPP WHERE PS_PARTKEY = 100;

EXPLAIN SELECT * FROM ORDERS WHERE O_ORDERDATE = '1995-03-15';
EXPLAIN SELECT * FROM PARTSUPP WHERE PS_PARTKEY = 100;

EXPLAIN SELECT * FROM ORDERS WHERE O_TOTALPRICE > 10000;
EXPLAIN SELECT * FROM LINEITEM WHERE L_SHIPDATE > '1996-01-01';
EXPLAIN SELECT * FROM CUSTOMER WHERE C_ACCTBAL > 500;
EXPLAIN SELECT * FROM PART WHERE P_SIZE = 10;
EXPLAIN SELECT * FROM SUPPLIER WHERE S_NATIONKEY = 3;

CREATE INDEX idx_orders_totalprice
ON ORDERS(O_TOTALPRICE);

EXPLAIN
SELECT *
FROM ORDERS
WHERE O_TOTALPRICE > 10000;

EXPLAIN
SELECT *
FROM ORDERS
WHERE O_TOTALPRICE > 50000;

EXPLAIN
SELECT *
FROM ORDERS
WHERE O_TOTALPRICE = 250000;

EXPLAIN SELECT * FROM LINEITEM WHERE L_SHIPDATE > '1996-01-01';
EXPLAIN SELECT * FROM PART WHERE P_SIZE = 10;

CREATE INDEX idx_lineitem_shipdate
ON LINEITEM(L_SHIPDATE);

EXPLAIN
SELECT *
FROM LINEITEM
WHERE L_SHIPDATE > '1996-01-01';

EXPLAIN
SELECT *
FROM LINEITEM
WHERE L_SHIPDATE = '1996-01-01';

EXPLAIN
SELECT *
FROM PART
WHERE P_SIZE = 10;

CREATE INDEX idx_part_size
ON PART(P_SIZE);

EXPLAIN
SELECT *
FROM PART
WHERE P_SIZE = 10;

USE tpch;

SELECT * 
FROM ORDERS