SELECT * FROM ORDERS WHERE O_TOTALPRICE > 10000;

SELECT * FROM ORDERS WHERE O_TOTALPRICE > 50000;

SELECT * FROM ORDERS WHERE O_TOTALPRICE BETWEEN 20000 AND 40000;

SELECT * FROM ORDERS WHERE O_ORDERDATE > '1995-01-01';

SELECT * FROM ORDERS WHERE O_ORDERDATE BETWEEN '1995-01-01' AND '1996-01-01';

SELECT O_ORDERKEY, O_ORDERDATE FROM ORDERS WHERE O_ORDERDATE > '1996-01-01';

SELECT O_ORDERKEY, O_CUSTKEY FROM ORDERS WHERE O_CUSTKEY = 1000;

SELECT * FROM ORDERS WHERE O_CUSTKEY BETWEEN 100 AND 500;

SELECT O_ORDERKEY, O_TOTALPRICE FROM ORDERS WHERE O_TOTALPRICE < 5000;

SELECT * FROM ORDERS WHERE O_ORDERSTATUS = 'O';

SELECT * FROM ORDERS WHERE O_TOTALPRICE > 15000 AND O_ORDERDATE > '1996-01-01';

SELECT O_ORDERKEY, O_TOTALPRICE FROM ORDERS WHERE O_TOTALPRICE >= 30000;

SELECT O_ORDERKEY, O_TOTALPRICE FROM ORDERS WHERE O_TOTALPRICE <= 15000;

SELECT O_ORDERKEY, O_ORDERDATE FROM ORDERS WHERE O_ORDERDATE BETWEEN '1994-01-01' AND '1995-01-01';

SELECT O_ORDERKEY, O_CUSTKEY FROM ORDERS WHERE O_CUSTKEY BETWEEN 500 AND 1000;

SELECT * FROM ORDERS WHERE O_TOTALPRICE > 20000 AND O_CUSTKEY < 500;

SELECT O_ORDERKEY FROM ORDERS WHERE O_TOTALPRICE > 5000;

SELECT O_ORDERKEY FROM ORDERS WHERE O_TOTALPRICE > 15000;

SELECT O_ORDERKEY FROM ORDERS WHERE O_TOTALPRICE > 25000;

SELECT O_ORDERKEY FROM ORDERS WHERE O_TOTALPRICE > 35000;

SELECT O_ORDERKEY FROM ORDERS WHERE O_TOTALPRICE > 45000;

SELECT O_ORDERKEY FROM ORDERS WHERE O_TOTALPRICE > 55000;

SELECT O_ORDERKEY, O_TOTALPRICE FROM ORDERS WHERE O_TOTALPRICE BETWEEN 5000 AND 15000;

SELECT O_ORDERKEY, O_TOTALPRICE FROM ORDERS WHERE O_TOTALPRICE BETWEEN 15000 AND 30000;

SELECT O_ORDERKEY, O_TOTALPRICE FROM ORDERS WHERE O_TOTALPRICE BETWEEN 30000 AND 60000;

SELECT O_ORDERKEY, O_TOTALPRICE FROM ORDERS WHERE O_TOTALPRICE BETWEEN 10000 AND 50000;

SELECT * FROM LINEITEM WHERE L_QUANTITY > 20;

SELECT * FROM LINEITEM WHERE L_QUANTITY BETWEEN 10 AND 30;

SELECT * FROM LINEITEM WHERE L_SHIPDATE > '1996-01-01';

SELECT * FROM LINEITEM WHERE L_DISCOUNT > 0.05;

SELECT * FROM LINEITEM WHERE L_QUANTITY > 30;

SELECT * FROM LINEITEM WHERE L_QUANTITY BETWEEN 5 AND 15;

SELECT L_ORDERKEY, L_PARTKEY FROM LINEITEM WHERE L_PARTKEY = 500;

SELECT * FROM LINEITEM WHERE L_SHIPDATE BETWEEN '1995-01-01' AND '1997-01-01';

SELECT * FROM LINEITEM WHERE L_DISCOUNT BETWEEN 0.02 AND 0.07;

SELECT L_ORDERKEY, L_QUANTITY FROM LINEITEM WHERE L_QUANTITY >= 25;

SELECT * FROM LINEITEM WHERE L_RETURNFLAG = 'R';

SELECT * FROM LINEITEM WHERE L_QUANTITY > 15 AND L_DISCOUNT > 0.03;

SELECT L_ORDERKEY, L_QUANTITY FROM LINEITEM WHERE L_QUANTITY < 10;

SELECT L_ORDERKEY, L_QUANTITY FROM LINEITEM WHERE L_QUANTITY >= 35;

SELECT * FROM LINEITEM WHERE L_SHIPDATE BETWEEN '1994-01-01' AND '1995-01-01';

SELECT * FROM LINEITEM WHERE L_DISCOUNT < 0.02;

SELECT * FROM LINEITEM WHERE L_QUANTITY > 20 AND L_SHIPDATE > '1996-01-01';

SELECT L_ORDERKEY FROM LINEITEM WHERE L_QUANTITY > 5;

SELECT L_ORDERKEY FROM LINEITEM WHERE L_QUANTITY > 10;

SELECT L_ORDERKEY FROM LINEITEM WHERE L_QUANTITY > 15;

SELECT L_ORDERKEY FROM LINEITEM WHERE L_QUANTITY > 25;

SELECT L_ORDERKEY FROM LINEITEM WHERE L_QUANTITY > 35;

SELECT L_ORDERKEY, L_QUANTITY FROM LINEITEM WHERE L_QUANTITY BETWEEN 1 AND 10;

SELECT L_ORDERKEY, L_QUANTITY FROM LINEITEM WHERE L_QUANTITY BETWEEN 10 AND 20;

SELECT L_ORDERKEY, L_QUANTITY FROM LINEITEM WHERE L_QUANTITY BETWEEN 20 AND 40;

SELECT L_ORDERKEY FROM LINEITEM WHERE L_QUANTITY BETWEEN 30 AND 50;

SELECT L_ORDERKEY FROM LINEITEM WHERE L_DISCOUNT > 0.08;

SELECT * FROM CUSTOMER WHERE C_ACCTBAL > 1000;

SELECT * FROM CUSTOMER WHERE C_ACCTBAL > 500;

SELECT * FROM CUSTOMER WHERE C_NATIONKEY = 10;

SELECT * FROM CUSTOMER WHERE C_ACCTBAL BETWEEN 200 AND 800;

SELECT * FROM CUSTOMER WHERE C_NATIONKEY BETWEEN 1 AND 10;

SELECT C_CUSTKEY, C_NAME FROM CUSTOMER WHERE C_NATIONKEY = 5;

SELECT * FROM CUSTOMER WHERE C_MKTSEGMENT = 'BUILDING';

SELECT C_CUSTKEY, C_NAME FROM CUSTOMER WHERE C_ACCTBAL < 300;

SELECT C_CUSTKEY, C_ACCTBAL FROM CUSTOMER WHERE C_ACCTBAL >= 1200;

SELECT * FROM CUSTOMER WHERE C_ACCTBAL < 200;

SELECT * FROM CUSTOMER WHERE C_NATIONKEY = 3;

SELECT C_CUSTKEY, C_NAME FROM CUSTOMER WHERE C_ACCTBAL BETWEEN 400 AND 900;

SELECT C_CUSTKEY, C_NAME FROM CUSTOMER WHERE C_NAME LIKE 'Customer#000%';

SELECT C_CUSTKEY FROM CUSTOMER WHERE C_ACCTBAL > 100;

SELECT C_CUSTKEY FROM CUSTOMER WHERE C_ACCTBAL > 300;

SELECT C_CUSTKEY FROM CUSTOMER WHERE C_ACCTBAL > 700;

SELECT C_CUSTKEY FROM CUSTOMER WHERE C_ACCTBAL > 1500;

SELECT C_CUSTKEY FROM CUSTOMER WHERE C_ACCTBAL > 2000;

SELECT C_CUSTKEY, C_ACCTBAL FROM CUSTOMER WHERE C_ACCTBAL BETWEEN 100 AND 500;

SELECT C_CUSTKEY, C_ACCTBAL FROM CUSTOMER WHERE C_ACCTBAL BETWEEN 500 AND 1000;

SELECT C_CUSTKEY FROM CUSTOMER WHERE C_NATIONKEY BETWEEN 6 AND 12;

SELECT * FROM PART WHERE P_SIZE = 10;

SELECT * FROM PART WHERE P_SIZE = 20;

SELECT * FROM PART WHERE P_SIZE BETWEEN 5 AND 15;

SELECT * FROM PART WHERE P_RETAILPRICE > 500;

SELECT * FROM PART WHERE P_RETAILPRICE > 1000;

SELECT * FROM PART WHERE P_RETAILPRICE BETWEEN 200 AND 800;

SELECT * FROM PART WHERE P_SIZE >= 15;

SELECT P_PARTKEY, P_NAME FROM PART WHERE P_RETAILPRICE < 300;

SELECT P_PARTKEY, P_SIZE FROM PART WHERE P_SIZE < 5;

SELECT * FROM PART WHERE P_RETAILPRICE >= 1200;

SELECT P_PARTKEY, P_RETAILPRICE FROM PART WHERE P_RETAILPRICE <= 300;

SELECT P_PARTKEY, P_NAME FROM PART WHERE P_NAME LIKE '%green%';

SELECT P_PARTKEY FROM PART WHERE P_SIZE > 5;

SELECT P_PARTKEY FROM PART WHERE P_SIZE > 10;

SELECT P_PARTKEY FROM PART WHERE P_SIZE > 15;

SELECT P_PARTKEY FROM PART WHERE P_SIZE > 20;

SELECT P_PARTKEY, P_RETAILPRICE FROM PART WHERE P_RETAILPRICE > 200;

SELECT P_PARTKEY, P_RETAILPRICE FROM PART WHERE P_RETAILPRICE > 600;

SELECT P_PARTKEY, P_RETAILPRICE FROM PART WHERE P_RETAILPRICE > 1200;

SELECT P_PARTKEY, P_RETAILPRICE FROM PART WHERE P_RETAILPRICE > 1500;

SELECT P_PARTKEY FROM PART WHERE P_SIZE BETWEEN 10 AND 30;

SELECT * FROM SUPPLIER WHERE S_ACCTBAL > 1000;

SELECT * FROM SUPPLIER WHERE S_ACCTBAL BETWEEN 500 AND 1500;

SELECT S_SUPPKEY, S_NAME FROM SUPPLIER WHERE S_NATIONKEY = 3;

SELECT * FROM SUPPLIER WHERE S_ACCTBAL < 500;

SELECT S_SUPPKEY, S_PHONE FROM SUPPLIER WHERE S_NATIONKEY BETWEEN 5 AND 10;

SELECT * FROM SUPPLIER WHERE S_ACCTBAL >= 2000;

SELECT * FROM SUPPLIER WHERE S_NATIONKEY = 7;

SELECT S_SUPPKEY, S_ACCTBAL FROM SUPPLIER WHERE S_ACCTBAL BETWEEN 200 AND 800;

SELECT S_SUPPKEY FROM SUPPLIER WHERE S_ACCTBAL > 100;

SELECT S_SUPPKEY FROM SUPPLIER WHERE S_ACCTBAL > 500;

SELECT S_SUPPKEY FROM SUPPLIER WHERE S_ACCTBAL > 1000;

SELECT S_SUPPKEY FROM SUPPLIER WHERE S_ACCTBAL > 1500;

SELECT S_SUPPKEY FROM SUPPLIER WHERE S_ACCTBAL > 1800;

SELECT S_SUPPKEY, S_ACCTBAL FROM SUPPLIER WHERE S_ACCTBAL BETWEEN 100 AND 600;

SELECT S_SUPPKEY, S_ACCTBAL FROM SUPPLIER WHERE S_ACCTBAL BETWEEN 600 AND 1200;

SELECT S_SUPPKEY FROM SUPPLIER WHERE S_NATIONKEY BETWEEN 1 AND 5;