SELECT o.O_ORDERKEY, c.C_NAME, n.N_NAME        AS nation FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY;

SELECT o.O_ORDERKEY, c.C_NAME, o.O_TOTALPRICE FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY WHERE  n.N_NAME = 'GERMANY';

SELECT o.O_ORDERKEY, c.C_NAME, n.N_NAME        AS nation FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY WHERE  o.O_TOTALPRICE > 100000;

SELECT o.O_ORDERKEY, c.C_NAME, n.N_NAME        AS nation FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY WHERE  c.C_ACCTBAL > 5000;

SELECT o.O_ORDERKEY, c.C_NAME, n.N_NAME        AS nation FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY WHERE  o.O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31';

SELECT o.O_ORDERKEY, c.C_NAME, o.O_TOTALPRICE FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY WHERE  n.N_NAME       = 'FRANCE' AND  o.O_TOTALPRICE > 50000;

SELECT o.O_ORDERKEY, c.C_NAME, c.C_ACCTBAL FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY WHERE  n.N_NAME       = 'UNITED STATES' AND  c.C_ACCTBAL   > 3000 AND  o.O_ORDERDATE > '1996-01-01';

SELECT o.O_ORDERKEY, c.C_NAME, n.N_NAME        AS nation, o.O_TOTALPRICE FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY ORDER BY o.O_TOTALPRICE DESC LIMIT  20;

SELECT n.N_NAME        AS nation, COUNT(o.O_ORDERKEY)  AS order_count, SUM(o.O_TOTALPRICE)  AS total_revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY GROUP BY n.N_NAME ORDER BY total_revenue DESC;

SELECT n.N_NAME        AS nation, COUNT(o.O_ORDERKEY)  AS order_count FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY GROUP BY n.N_NAME HAVING COUNT(o.O_ORDERKEY) > 1000 ORDER BY order_count DESC;

SELECT o.O_ORDERKEY, c.C_NAME, n.N_NAME        AS nation, r.R_NAME        AS region FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY;

SELECT o.O_ORDERKEY, c.C_NAME, n.N_NAME        AS nation FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY WHERE  r.R_NAME = 'EUROPE';

SELECT o.O_ORDERKEY, c.C_NAME, o.O_TOTALPRICE FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY WHERE  r.R_NAME       = 'ASIA' AND  o.O_TOTALPRICE > 80000;

SELECT r.R_NAME        AS region, SUM(o.O_TOTALPRICE)  AS total_revenue, COUNT(o.O_ORDERKEY)  AS order_count FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY GROUP BY r.R_NAME ORDER BY total_revenue DESC;

SELECT r.R_NAME        AS region, n.N_NAME        AS nation, SUM(o.O_TOTALPRICE)  AS total_revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY WHERE  r.R_NAME = 'AMERICA' GROUP BY r.R_NAME, n.N_NAME ORDER BY total_revenue DESC;

SELECT r.R_NAME        AS region, AVG(o.O_TOTALPRICE)  AS avg_order_value FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY GROUP BY r.R_NAME;

SELECT r.R_NAME        AS region, c.C_NAME, SUM(o.O_TOTALPRICE)  AS total_spent FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY GROUP BY r.R_NAME, c.C_CUSTKEY, c.C_NAME ORDER BY r.R_NAME, total_spent DESC;

SELECT r.R_NAME        AS region, SUM(o.O_TOTALPRICE)  AS revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY WHERE  o.O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31' GROUP BY r.R_NAME;

SELECT r.R_NAME        AS region, SUM(o.O_TOTALPRICE)  AS total_revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY GROUP BY r.R_NAME HAVING SUM(o.O_TOTALPRICE) > 50000000;

SELECT DISTINCT r.R_NAME   AS region, n.N_NAME             AS nation FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY WHERE  c.C_ACCTBAL > 8000 ORDER BY r.R_NAME, n.N_NAME;

SELECT o.O_ORDERKEY, p.P_NAME, l.L_QUANTITY FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART    p  ON l.L_PARTKEY  = p.P_PARTKEY WHERE  p.P_SIZE > 20;

SELECT o.O_ORDERKEY, p.P_TYPE, l.L_EXTENDEDPRICE FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART    p  ON l.L_PARTKEY  = p.P_PARTKEY WHERE  p.P_TYPE LIKE 'STANDARD%';

SELECT o.O_ORDERKEY, p.P_NAME, l.L_QUANTITY FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART    p  ON l.L_PARTKEY  = p.P_PARTKEY WHERE  l.L_QUANTITY > 30 AND  p.P_SIZE     > 15;

SELECT o.O_ORDERKEY, p.P_RETAILPRICE, l.L_SHIPDATE FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART    p  ON l.L_PARTKEY  = p.P_PARTKEY WHERE  l.L_SHIPDATE    > '1996-01-01' AND  p.P_RETAILPRICE > 1000;

SELECT p.P_BRAND, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART    p  ON l.L_PARTKEY  = p.P_PARTKEY GROUP BY p.P_BRAND ORDER BY revenue DESC;

SELECT p.P_TYPE, AVG(l.L_QUANTITY)    AS avg_quantity, COUNT(l.L_LINENUMBER) AS line_count FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART    p  ON l.L_PARTKEY  = p.P_PARTKEY GROUP BY p.P_TYPE;

SELECT p.P_PARTKEY, p.P_NAME, SUM(l.L_QUANTITY)    AS total_qty FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART    p  ON l.L_PARTKEY  = p.P_PARTKEY GROUP BY p.P_PARTKEY, p.P_NAME ORDER BY total_qty DESC LIMIT  10;

SELECT o.O_ORDERKEY, o.O_TOTALPRICE, MAX(p.P_RETAILPRICE) AS max_part_price FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART    p  ON l.L_PARTKEY  = p.P_PARTKEY GROUP BY o.O_ORDERKEY, o.O_TOTALPRICE HAVING MAX(p.P_RETAILPRICE) > 1500 ORDER BY o.O_TOTALPRICE DESC LIMIT  25;

SELECT DISTINCT p.P_BRAND FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART    p  ON l.L_PARTKEY  = p.P_PARTKEY WHERE  o.O_TOTALPRICE > 200000 ORDER BY p.P_BRAND;

SELECT o.O_ORDERKEY, s.S_NAME, l.L_EXTENDEDPRICE FROM   ORDERS   o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   SUPPLIER s ON l.L_SUPPKEY  = s.S_SUPPKEY WHERE  s.S_NATIONKEY = 1;

SELECT o.O_ORDERKEY, s.S_NAME, l.L_QUANTITY FROM   ORDERS   o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   SUPPLIER s ON l.L_SUPPKEY  = s.S_SUPPKEY WHERE  s.S_ACCTBAL > 5000;

SELECT o.O_ORDERKEY, s.S_NAME, l.L_DISCOUNT FROM   ORDERS   o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   SUPPLIER s ON l.L_SUPPKEY  = s.S_SUPPKEY WHERE  l.L_DISCOUNT   > 0.05 AND  o.O_TOTALPRICE > 50000;

SELECT s.S_SUPPKEY, s.S_NAME, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS   o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   SUPPLIER s ON l.L_SUPPKEY  = s.S_SUPPKEY GROUP BY s.S_SUPPKEY, s.S_NAME ORDER BY revenue DESC;

SELECT s.S_SUPPKEY, s.S_NAME, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS   o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   SUPPLIER s ON l.L_SUPPKEY  = s.S_SUPPKEY GROUP BY s.S_SUPPKEY, s.S_NAME ORDER BY revenue DESC LIMIT  10;

SELECT s.S_NATIONKEY, AVG(l.L_DISCOUNT)    AS avg_discount FROM   ORDERS   o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   SUPPLIER s ON l.L_SUPPKEY  = s.S_SUPPKEY GROUP BY s.S_NATIONKEY ORDER BY avg_discount DESC;

SELECT s.S_SUPPKEY, s.S_NAME, SUM(l.L_QUANTITY)    AS total_qty FROM   ORDERS   o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   SUPPLIER s ON l.L_SUPPKEY  = s.S_SUPPKEY GROUP BY s.S_SUPPKEY, s.S_NAME HAVING SUM(l.L_QUANTITY) > 10000;

SELECT o.O_ORDERKEY, s.S_NAME, l.L_SHIPDATE FROM   ORDERS   o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   SUPPLIER s ON l.L_SUPPKEY  = s.S_SUPPKEY WHERE  l.L_SHIPDATE BETWEEN '1995-01-01' AND '1997-01-01' AND  s.S_ACCTBAL  > 3000;

SELECT DISTINCT s.S_SUPPKEY, s.S_NAME FROM   ORDERS   o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   SUPPLIER s ON l.L_SUPPKEY  = s.S_SUPPKEY WHERE  o.O_TOTALPRICE > 150000 ORDER BY s.S_NAME;

SELECT l.L_ORDERKEY, p.P_NAME, ps.PS_SUPPLYCOST FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY;

SELECT l.L_ORDERKEY, p.P_NAME, ps.PS_SUPPLYCOST, l.L_EXTENDEDPRICE FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY WHERE  ps.PS_SUPPLYCOST < l.L_EXTENDEDPRICE;

SELECT l.L_ORDERKEY, p.P_NAME, ps.PS_SUPPLYCOST FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY WHERE  p.P_SIZE         > 15 AND  ps.PS_SUPPLYCOST > 400;

SELECT p.P_PARTKEY, p.P_NAME, SUM(l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST) AS total_margin FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY GROUP BY p.P_PARTKEY, p.P_NAME ORDER BY total_margin DESC LIMIT  20;

SELECT p.P_BRAND, AVG(l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST) AS avg_margin FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY GROUP BY p.P_BRAND ORDER BY avg_margin DESC;

SELECT p.P_PARTKEY, p.P_SIZE, ps.PS_SUPPLYCOST FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY JOIN   LINEITEM l  ON l.L_PARTKEY = p.P_PARTKEY AND l.L_SUPPKEY = ps.PS_SUPPKEY WHERE  ps.PS_SUPPLYCOST > 600 ORDER BY p.P_SIZE, ps.PS_SUPPLYCOST DESC;

SELECT p.P_TYPE, COUNT(l.L_LINENUMBER) AS line_count, AVG(ps.PS_SUPPLYCOST) AS avg_supply_cost FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY GROUP BY p.P_TYPE ORDER BY line_count DESC;

SELECT p.P_BRAND, AVG(l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST) AS avg_margin FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY GROUP BY p.P_BRAND HAVING AVG(l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST) > 500;

SELECT l.L_ORDERKEY, p.P_NAME, l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST AS margin FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY WHERE  l.L_SHIPDATE > '1996-01-01' ORDER BY margin DESC LIMIT  30;

SELECT DISTINCT p.P_TYPE, p.P_BRAND FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY WHERE  ps.PS_AVAILQTY > 200 ORDER BY p.P_TYPE;

SELECT l.L_ORDERKEY, p.P_NAME, s.S_NAME, ps.PS_SUPPLYCOST FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   SUPPLIER s  ON l.L_SUPPKEY  = s.S_SUPPKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY;

SELECT l.L_ORDERKEY, p.P_NAME, s.S_NAME FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   SUPPLIER s  ON l.L_SUPPKEY  = s.S_SUPPKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY WHERE  s.S_NATIONKEY = 5 AND  p.P_SIZE      > 10;

SELECT s.S_NAME, p.P_TYPE, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   SUPPLIER s  ON l.L_SUPPKEY  = s.S_SUPPKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY GROUP BY s.S_SUPPKEY, s.S_NAME, p.P_TYPE ORDER BY s.S_NAME, revenue DESC;

SELECT s.S_SUPPKEY, s.S_NAME, SUM(l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST) AS total_margin FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   SUPPLIER s  ON l.L_SUPPKEY  = s.S_SUPPKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY GROUP BY s.S_SUPPKEY, s.S_NAME ORDER BY total_margin DESC LIMIT  15;

SELECT l.L_ORDERKEY, p.P_NAME, s.S_NAME, l.L_QUANTITY FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   SUPPLIER s  ON l.L_SUPPKEY  = s.S_SUPPKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY WHERE  ps.PS_SUPPLYCOST > 500 AND  l.L_DISCOUNT     > 0.04 AND  l.L_QUANTITY     > 20;

SELECT p.P_BRAND, s.S_NATIONKEY, AVG(ps.PS_SUPPLYCOST) AS avg_cost FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   SUPPLIER s  ON l.L_SUPPKEY  = s.S_SUPPKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY GROUP BY p.P_BRAND, s.S_NATIONKEY ORDER BY p.P_BRAND, s.S_NATIONKEY;

SELECT s.S_SUPPKEY, s.S_NAME, AVG(l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST) AS avg_margin FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   SUPPLIER s  ON l.L_SUPPKEY  = s.S_SUPPKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY GROUP BY s.S_SUPPKEY, s.S_NAME HAVING AVG(l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST) > 800;

SELECT p.P_NAME, s.S_NAME, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   SUPPLIER s  ON l.L_SUPPKEY  = s.S_SUPPKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY GROUP BY p.P_PARTKEY, p.P_NAME, s.S_SUPPKEY, s.S_NAME ORDER BY revenue DESC LIMIT  20;

SELECT DISTINCT p.P_BRAND, s.S_NATIONKEY FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   SUPPLIER s  ON l.L_SUPPKEY  = s.S_SUPPKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY WHERE  l.L_SHIPDATE > '1997-01-01' ORDER BY p.P_BRAND;

SELECT p.P_BRAND, s.S_NATIONKEY, COUNT(DISTINCT l.L_ORDERKEY) AS order_count FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   SUPPLIER s  ON l.L_SUPPKEY  = s.S_SUPPKEY JOIN   PARTSUPP ps ON l.L_PARTKEY  = ps.PS_PARTKEY AND l.L_SUPPKEY  = ps.PS_SUPPKEY WHERE  l.L_SHIPDATE BETWEEN '1994-01-01' AND '1998-12-31' GROUP BY p.P_BRAND, s.S_NATIONKEY;

SELECT o.O_ORDERKEY, c.C_NAME, l.L_QUANTITY FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  c.C_ACCTBAL  > 5000 AND  l.L_QUANTITY > 30;

SELECT o.O_ORDERKEY, c.C_NAME, l.L_DISCOUNT FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  c.C_NATIONKEY  = 10 AND  l.L_DISCOUNT   > 0.05 AND  o.O_ORDERDATE  > '1995-01-01';

SELECT c.C_CUSTKEY, c.C_NAME, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS total_spend FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY c.C_CUSTKEY, c.C_NAME ORDER BY total_spend DESC;

SELECT c.C_CUSTKEY, c.C_NAME, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS total_spend FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY c.C_CUSTKEY, c.C_NAME ORDER BY total_spend DESC LIMIT  15;

SELECT c.C_NATIONKEY, AVG(l.L_QUANTITY)    AS avg_quantity FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY c.C_NATIONKEY ORDER BY avg_quantity DESC;

SELECT c.C_CUSTKEY, c.C_NAME, COUNT(l.L_LINENUMBER) AS total_lines FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY c.C_CUSTKEY, c.C_NAME HAVING COUNT(l.L_LINENUMBER) > 50 ORDER BY total_lines DESC;

SELECT c.C_NATIONKEY, YEAR(o.O_ORDERDATE)  AS order_year, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY c.C_NATIONKEY, YEAR(o.O_ORDERDATE) ORDER BY c.C_NATIONKEY, order_year;

SELECT o.O_ORDERKEY, c.C_NAME, l.L_DISCOUNT, l.L_EXTENDEDPRICE FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  c.C_ACCTBAL > 7000 AND  l.L_DISCOUNT > 0.07 ORDER BY l.L_DISCOUNT DESC LIMIT  50;

SELECT DISTINCT c.C_NATIONKEY FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_RECEIPTDATE > l.L_COMMITDATE ORDER BY c.C_NATIONKEY;

SELECT s.S_SUPPKEY, s.S_NAME, n.N_NAME        AS nation, r.R_NAME        AS region FROM   SUPPLIER s JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY;

SELECT s.S_SUPPKEY, s.S_NAME, n.N_NAME        AS nation FROM   SUPPLIER s JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  r.R_NAME = 'EUROPE';

SELECT s.S_SUPPKEY, s.S_NAME, s.S_ACCTBAL FROM   SUPPLIER s JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  n.N_NAME    = 'GERMANY' AND  s.S_ACCTBAL > 4000;

SELECT r.R_NAME        AS region, COUNT(s.S_SUPPKEY) AS supplier_count FROM   SUPPLIER s JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY r.R_NAME ORDER BY supplier_count DESC;

SELECT n.N_NAME        AS nation, AVG(s.S_ACCTBAL) AS avg_balance, COUNT(s.S_SUPPKEY) AS supplier_count FROM   SUPPLIER s JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY n.N_NATIONKEY, n.N_NAME ORDER BY avg_balance DESC;

SELECT r.R_NAME        AS region, MAX(s.S_ACCTBAL) AS max_balance FROM   SUPPLIER s JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY r.R_NAME;

SELECT s.S_NAME, n.N_NAME        AS nation, r.R_NAME        AS region, s.S_ACCTBAL FROM   SUPPLIER s JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY ORDER BY s.S_ACCTBAL DESC LIMIT  10;

SELECT n.N_NAME        AS nation, COUNT(s.S_SUPPKEY) AS supplier_count FROM   SUPPLIER s JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY n.N_NATIONKEY, n.N_NAME HAVING COUNT(s.S_SUPPKEY) > 10 ORDER BY supplier_count DESC;

SELECT DISTINCT r.R_NAME   AS region FROM   SUPPLIER s JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  s.S_ACCTBAL > 9000;

SELECT s.S_NAME, n.N_NAME        AS nation, s.S_ACCTBAL FROM   SUPPLIER s JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  r.R_NAME    = 'ASIA' AND  s.S_ACCTBAL BETWEEN 2000 AND 8000 ORDER BY s.S_ACCTBAL DESC;

SELECT c.C_CUSTKEY, c.C_NAME, n.N_NAME        AS nation, r.R_NAME        AS region FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY;

SELECT c.C_CUSTKEY, c.C_NAME, n.N_NAME        AS nation FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  r.R_NAME = 'MIDDLE EAST';

SELECT c.C_CUSTKEY, c.C_NAME, c.C_ACCTBAL FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  r.R_NAME    = 'AMERICA' AND  c.C_ACCTBAL > 6000;

SELECT r.R_NAME        AS region, COUNT(c.C_CUSTKEY) AS customer_count FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY r.R_NAME ORDER BY customer_count DESC;

SELECT n.N_NAME        AS nation, AVG(c.C_ACCTBAL) AS avg_balance FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY n.N_NATIONKEY, n.N_NAME ORDER BY avg_balance DESC;

SELECT r.R_NAME        AS region, SUM(c.C_ACCTBAL) AS total_balance, COUNT(c.C_CUSTKEY) AS customer_count FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY r.R_NAME;

SELECT c.C_NAME, n.N_NAME        AS nation, r.R_NAME        AS region, c.C_ACCTBAL FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY ORDER BY c.C_ACCTBAL DESC LIMIT  20;

SELECT n.N_NAME        AS nation, AVG(c.C_ACCTBAL) AS avg_balance FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY n.N_NATIONKEY, n.N_NAME HAVING AVG(c.C_ACCTBAL) > 4000;

SELECT r.R_NAME        AS region, COUNT(c.C_CUSTKEY) AS high_balance_count FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  c.C_ACCTBAL > 5000 GROUP BY r.R_NAME ORDER BY high_balance_count DESC;

SELECT DISTINCT r.R_NAME   AS region, n.N_NAME             AS nation FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  n.N_NAME IN ('GERMANY', 'FRANCE', 'UNITED KINGDOM') ORDER BY r.R_NAME;

SELECT o.O_ORDERKEY, c.C_NAME, p.P_TYPE, l.L_QUANTITY FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY WHERE  c.C_NATIONKEY  = 5 AND  p.P_TYPE       LIKE 'ECONOMY%' AND  o.O_ORDERDATE  > '1995-01-01';

SELECT c.C_CUSTKEY, c.C_NAME, p.P_BRAND, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY GROUP BY c.C_CUSTKEY, c.C_NAME, p.P_BRAND ORDER BY revenue DESC LIMIT  20;

SELECT c.C_NATIONKEY, p.P_TYPE, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY GROUP BY c.C_NATIONKEY, p.P_TYPE ORDER BY c.C_NATIONKEY, revenue DESC;

SELECT c.C_NATIONKEY, p.P_BRAND, SUM(l.L_QUANTITY)    AS total_qty FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY GROUP BY c.C_NATIONKEY, p.P_BRAND ORDER BY c.C_NATIONKEY, total_qty DESC;

SELECT c.C_NATIONKEY, p.P_BRAND, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY GROUP BY c.C_NATIONKEY, p.P_BRAND HAVING SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) > 1000000;

SELECT o.O_ORDERKEY, c.C_NAME, p.P_NAME, l.L_DISCOUNT FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY WHERE  c.C_ACCTBAL > 6000 AND  p.P_SIZE    > 25 AND  l.L_DISCOUNT > 0.06 ORDER BY l.L_DISCOUNT DESC;

SELECT DISTINCT c.C_NATIONKEY, p.P_TYPE FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY ORDER BY c.C_NATIONKEY, p.P_TYPE;

SELECT YEAR(o.O_ORDERDATE) AS order_year, p.P_BRAND, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY GROUP BY YEAR(o.O_ORDERDATE), p.P_BRAND ORDER BY order_year, revenue DESC;

SELECT o.O_ORDERKEY, c.C_NAME, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS net_revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY GROUP BY o.O_ORDERKEY, c.C_NAME ORDER BY net_revenue DESC LIMIT  10;

SELECT r.R_NAME        AS region, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY JOIN   LINEITEM l ON o.O_ORDERKEY   = l.L_ORDERKEY WHERE  o.O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31' GROUP BY r.R_NAME ORDER BY revenue DESC;

SELECT n.N_NAME        AS supplier_nation, p.P_BRAND, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS   o JOIN   LINEITEM l ON o.O_ORDERKEY  = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY   = p.P_PARTKEY JOIN   SUPPLIER s ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY GROUP BY n.N_NAME, p.P_BRAND ORDER BY n.N_NAME, revenue DESC;

SELECT o.O_ORDERKEY, p.P_NAME, s.S_NAME, n.N_NAME        AS supplier_nation, l.L_EXTENDEDPRICE FROM   ORDERS   o JOIN   LINEITEM l ON o.O_ORDERKEY  = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY   = p.P_PARTKEY JOIN   SUPPLIER s ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY WHERE  n.N_NAME         IN ('GERMANY', 'FRANCE') AND  p.P_SIZE         > 20 AND  l.L_SHIPDATE     > '1996-01-01';

SELECT o.O_ORDERKEY, c.C_NAME, p.P_NAME, l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST AS margin FROM   ORDERS   o JOIN   CUSTOMER c  ON o.O_CUSTKEY   = c.C_CUSTKEY JOIN   LINEITEM l  ON o.O_ORDERKEY  = l.L_ORDERKEY JOIN   PART     p  ON l.L_PARTKEY   = p.P_PARTKEY JOIN   PARTSUPP ps ON l.L_PARTKEY   = ps.PS_PARTKEY AND l.L_SUPPKEY   = ps.PS_SUPPKEY ORDER BY margin DESC LIMIT  25;

SELECT c.C_CUSTKEY, c.C_NAME, SUM(l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST) AS total_margin FROM   ORDERS   o JOIN   CUSTOMER c  ON o.O_CUSTKEY   = c.C_CUSTKEY JOIN   LINEITEM l  ON o.O_ORDERKEY  = l.L_ORDERKEY JOIN   PART     p  ON l.L_PARTKEY   = p.P_PARTKEY JOIN   PARTSUPP ps ON l.L_PARTKEY   = ps.PS_PARTKEY AND l.L_SUPPKEY   = ps.PS_SUPPKEY GROUP BY c.C_CUSTKEY, c.C_NAME ORDER BY total_margin DESC LIMIT  20;

SELECT n.N_NAME        AS nation, p.P_TYPE, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   LINEITEM l ON o.O_ORDERKEY   = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY    = p.P_PARTKEY WHERE  o.O_ORDERDATE BETWEEN '1994-01-01' AND '1997-12-31' GROUP BY n.N_NAME, p.P_TYPE;

SELECT cn.N_NAME       AS cust_nation, sn.N_NAME       AS supp_nation, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY   = c.C_CUSTKEY JOIN   NATION    cn ON c.C_NATIONKEY = cn.N_NATIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY  = l.L_ORDERKEY JOIN   SUPPLIER  s  ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION    sn ON s.S_NATIONKEY = sn.N_NATIONKEY WHERE  o.O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31' GROUP BY cn.N_NAME, sn.N_NAME ORDER BY revenue DESC;

SELECT cn.N_NAME       AS nation, COUNT(DISTINCT o.O_ORDERKEY) AS order_count, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY   = c.C_CUSTKEY JOIN   NATION    cn ON c.C_NATIONKEY = cn.N_NATIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY  = l.L_ORDERKEY JOIN   SUPPLIER  s  ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION    sn ON s.S_NATIONKEY = sn.N_NATIONKEY WHERE  cn.N_NATIONKEY = sn.N_NATIONKEY GROUP BY cn.N_NAME ORDER BY revenue DESC;

SELECT n.N_NAME        AS nation, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   LINEITEM l ON o.O_ORDERKEY   = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY    = p.P_PARTKEY WHERE  p.P_SIZE > 20 GROUP BY n.N_NAME HAVING SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) > 5000000 ORDER BY revenue DESC;

SELECT o.O_ORDERKEY, c.C_NAME, cn.N_NAME       AS cust_nation, p.P_NAME, s.S_NAME, l.L_EXTENDEDPRICE FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY   = c.C_CUSTKEY JOIN   NATION    cn ON c.C_NATIONKEY = cn.N_NATIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY  = l.L_ORDERKEY JOIN   PART      p  ON l.L_PARTKEY   = p.P_PARTKEY JOIN   SUPPLIER  s  ON l.L_SUPPKEY   = s.S_SUPPKEY LIMIT  100;

SELECT cn.N_NAME       AS cust_nation, p.P_BRAND, s.S_NAME, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY   = c.C_CUSTKEY JOIN   NATION    cn ON c.C_NATIONKEY = cn.N_NATIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY  = l.L_ORDERKEY JOIN   PART      p  ON l.L_PARTKEY   = p.P_PARTKEY JOIN   SUPPLIER  s  ON l.L_SUPPKEY   = s.S_SUPPKEY WHERE  o.O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31' GROUP BY cn.N_NAME, p.P_BRAND, s.S_SUPPKEY, s.S_NAME ORDER BY revenue DESC LIMIT  20;

SELECT r.R_NAME        AS region, p.P_TYPE, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION    n  ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY  = r.R_REGIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY   = l.L_ORDERKEY JOIN   PART      p  ON l.L_PARTKEY    = p.P_PARTKEY GROUP BY r.R_NAME, p.P_TYPE ORDER BY r.R_NAME, revenue DESC;

SELECT r.R_NAME        AS customer_region, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue, AVG(s.S_ACCTBAL)                              AS avg_supplier_balance FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION    n  ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY  = r.R_REGIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY   = l.L_ORDERKEY JOIN   SUPPLIER  s  ON l.L_SUPPKEY    = s.S_SUPPKEY GROUP BY r.R_NAME ORDER BY revenue DESC;

SELECT cn.N_NAME       AS cust_nation, p.P_BRAND, SUM(l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST) AS total_margin FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION    cn ON c.C_NATIONKEY  = cn.N_NATIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY   = l.L_ORDERKEY JOIN   PART      p  ON l.L_PARTKEY    = p.P_PARTKEY JOIN   PARTSUPP  ps ON l.L_PARTKEY    = ps.PS_PARTKEY AND l.L_SUPPKEY    = ps.PS_SUPPKEY GROUP BY cn.N_NAME, p.P_BRAND ORDER BY total_margin DESC;

SELECT r.R_NAME        AS region, p.P_BRAND, SUM(l.L_QUANTITY) AS total_qty FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION    n  ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY  = r.R_REGIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY   = l.L_ORDERKEY JOIN   PART      p  ON l.L_PARTKEY    = p.P_PARTKEY GROUP BY r.R_NAME, p.P_BRAND ORDER BY r.R_NAME, total_qty DESC;

SELECT cn.N_NAME       AS cust_nation, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY   = c.C_CUSTKEY JOIN   NATION    cn ON c.C_NATIONKEY = cn.N_NATIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY  = l.L_ORDERKEY JOIN   PART      p  ON l.L_PARTKEY   = p.P_PARTKEY JOIN   SUPPLIER  s  ON l.L_SUPPKEY   = s.S_SUPPKEY GROUP BY cn.N_NAME HAVING SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) > 10000000 ORDER BY revenue DESC;

SELECT r.R_NAME        AS region, p.P_BRAND, COUNT(DISTINCT c.C_CUSTKEY) AS cust_count FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION    n  ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY  = r.R_REGIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY   = l.L_ORDERKEY JOIN   PART      p  ON l.L_PARTKEY    = p.P_PARTKEY GROUP BY r.R_NAME, p.P_BRAND ORDER BY r.R_NAME, cust_count DESC;

SELECT cn.N_NAME       AS cust_nation, sn.N_NAME       AS supp_nation, AVG(o.O_TOTALPRICE) AS avg_order_value FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY   = c.C_CUSTKEY JOIN   NATION    cn ON c.C_NATIONKEY = cn.N_NATIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY  = l.L_ORDERKEY JOIN   SUPPLIER  s  ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION    sn ON s.S_NATIONKEY = sn.N_NATIONKEY GROUP BY cn.N_NAME, sn.N_NAME ORDER BY cn.N_NAME, avg_order_value DESC;

SELECT r.R_NAME                 AS region, YEAR(o.O_ORDERDATE)      AS yr, MONTH(o.O_ORDERDATE)     AS mo, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION    n  ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY  = r.R_REGIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY   = l.L_ORDERKEY JOIN   PART      p  ON l.L_PARTKEY    = p.P_PARTKEY WHERE  o.O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31' GROUP BY r.R_NAME, YEAR(o.O_ORDERDATE), MONTH(o.O_ORDERDATE) ORDER BY r.R_NAME, yr, mo;

SELECT p.P_BRAND, n.N_NAME        AS supplier_nation, MAX(l.L_EXTENDEDPRICE) AS max_price, MIN(l.L_EXTENDEDPRICE) AS min_price FROM   LINEITEM l JOIN   PART     p ON l.L_PARTKEY   = p.P_PARTKEY JOIN   SUPPLIER s ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY GROUP BY p.P_BRAND, n.N_NAME ORDER BY p.P_BRAND;

SELECT c.C_MKTSEGMENT, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS net_revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY c.C_MKTSEGMENT ORDER BY net_revenue DESC;

SELECT p.P_SIZE, r.R_NAME        AS supplier_region, AVG(l.L_DISCOUNT) AS avg_discount FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY   = p.P_PARTKEY JOIN   SUPPLIER s  ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r  ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY p.P_SIZE, r.R_NAME ORDER BY p.P_SIZE, avg_discount DESC;

SELECT r.R_NAME        AS region, SUM(ps.PS_AVAILQTY * ps.PS_SUPPLYCOST) AS stock_value FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY   = ps.PS_SUPPKEY JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r  ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY r.R_NAME ORDER BY stock_value DESC;

SELECT l.L_SHIPMODE, p.P_TYPE, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART    p  ON l.L_PARTKEY  = p.P_PARTKEY GROUP BY l.L_SHIPMODE, p.P_TYPE ORDER BY l.L_SHIPMODE, revenue DESC;

SELECT c.C_MKTSEGMENT, YEAR(o.O_ORDERDATE) AS order_year, COUNT(o.O_ORDERKEY)  AS order_count FROM   CUSTOMER c JOIN   ORDERS   o ON c.C_CUSTKEY = o.O_CUSTKEY GROUP BY c.C_MKTSEGMENT, YEAR(o.O_ORDERDATE) ORDER BY c.C_MKTSEGMENT, order_year;

SELECT p.P_CONTAINER, n.N_NAME        AS nation, SUM(l.L_QUANTITY) AS total_qty FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY   = p.P_PARTKEY JOIN   SUPPLIER s  ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY GROUP BY p.P_CONTAINER, n.N_NAME ORDER BY total_qty DESC;

SELECT c.C_MKTSEGMENT, n.N_NAME        AS nation, MAX(o.O_TOTALPRICE) AS max_order FROM   CUSTOMER c JOIN   ORDERS   o ON c.C_CUSTKEY   = o.O_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY GROUP BY c.C_MKTSEGMENT, n.N_NAME;

SELECT p.P_CONTAINER, r.R_NAME        AS region, AVG(ps.PS_SUPPLYCOST) AS avg_cost FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY   = ps.PS_PARTKEY JOIN   SUPPLIER s  ON ps.PS_SUPPKEY = s.S_SUPPKEY JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r  ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY p.P_CONTAINER, r.R_NAME ORDER BY p.P_CONTAINER;

SELECT c.C_MKTSEGMENT, YEAR(o.O_ORDERDATE)   AS yr, MONTH(o.O_ORDERDATE)  AS mo, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY c.C_MKTSEGMENT, YEAR(o.O_ORDERDATE), MONTH(o.O_ORDERDATE) ORDER BY c.C_MKTSEGMENT, yr, mo;

SELECT p.P_BRAND, YEAR(l.L_SHIPDATE)    AS ship_year, MAX(l.L_QUANTITY) - MIN(l.L_QUANTITY) AS qty_spread FROM   LINEITEM l JOIN   PART     p ON l.L_PARTKEY = p.P_PARTKEY JOIN   ORDERS   o ON l.L_ORDERKEY = o.O_ORDERKEY GROUP BY p.P_BRAND, YEAR(l.L_SHIPDATE) ORDER BY p.P_BRAND, ship_year;

SELECT p.P_TYPE, COUNT(DISTINCT c.C_CUSTKEY) AS customer_count FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY GROUP BY p.P_TYPE ORDER BY customer_count DESC;

SELECT p.P_BRAND, r.R_NAME        AS region, SUM(ps.PS_AVAILQTY * ps.PS_SUPPLYCOST) AS stock_value FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY   = ps.PS_PARTKEY JOIN   SUPPLIER s  ON ps.PS_SUPPKEY = s.S_SUPPKEY JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r  ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY p.P_BRAND, r.R_NAME ORDER BY p.P_BRAND, stock_value DESC;

SELECT r.R_NAME        AS region, o.O_ORDERSTATUS  AS status, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION    n  ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY  = r.R_REGIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY   = l.L_ORDERKEY GROUP BY r.R_NAME, o.O_ORDERSTATUS ORDER BY r.R_NAME, revenue DESC;

SELECT n.N_NAME        AS nation, SUM(o.O_TOTALPRICE)   AS total_revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY GROUP BY n.N_NAME HAVING SUM(o.O_TOTALPRICE) > 1000000000 ORDER BY total_revenue DESC;

SELECT s.S_SUPPKEY, s.S_NAME, COUNT(ps.PS_PARTKEY) AS part_count FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY   = ps.PS_SUPPKEY JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY GROUP BY s.S_SUPPKEY, s.S_NAME HAVING COUNT(ps.PS_PARTKEY) > 5 ORDER BY part_count DESC;

SELECT p.P_BRAND, AVG(l.L_EXTENDEDPRICE) AS avg_line_revenue FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY  = p.P_PARTKEY JOIN   ORDERS   o  ON l.L_ORDERKEY = o.O_ORDERKEY GROUP BY p.P_BRAND HAVING AVG(l.L_EXTENDEDPRICE) > 30000 ORDER BY avg_line_revenue DESC;

SELECT r.R_NAME        AS region, COUNT(c.C_CUSTKEY) AS customer_count FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY r.R_NAME HAVING COUNT(c.C_CUSTKEY) > 200000;

SELECT p.P_TYPE, COUNT(l.L_LINENUMBER) AS line_count FROM   LINEITEM l JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY JOIN   ORDERS   o ON l.L_ORDERKEY = o.O_ORDERKEY GROUP BY p.P_TYPE HAVING COUNT(l.L_LINENUMBER) > 100000 ORDER BY line_count DESC;

SELECT c.C_MKTSEGMENT, n.N_NAME        AS nation, AVG(c.C_ACCTBAL) AS avg_balance FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   ORDERS   o ON c.C_CUSTKEY   = o.O_CUSTKEY GROUP BY c.C_MKTSEGMENT, n.N_NATIONKEY, n.N_NAME HAVING AVG(c.C_ACCTBAL) > 5000 ORDER BY avg_balance DESC;

SELECT n.N_NAME        AS nation, SUM(ps.PS_AVAILQTY) AS total_stock FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY   = ps.PS_SUPPKEY JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY GROUP BY n.N_NATIONKEY, n.N_NAME HAVING SUM(ps.PS_AVAILQTY) > 500000 ORDER BY total_stock DESC;

SELECT p.P_CONTAINER, AVG(ps.PS_SUPPLYCOST) AS avg_cost, COUNT(DISTINCT p.P_PARTKEY) AS part_count FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY   = ps.PS_PARTKEY JOIN   SUPPLIER s  ON ps.PS_SUPPKEY = s.S_SUPPKEY GROUP BY p.P_CONTAINER HAVING AVG(ps.PS_SUPPLYCOST) < 300 ORDER BY avg_cost ASC;

SELECT l.L_SHIPMODE, AVG(l.L_QUANTITY)    AS avg_qty, COUNT(l.L_LINENUMBER) AS line_count FROM   LINEITEM l JOIN   ORDERS   o ON l.L_ORDERKEY = o.O_ORDERKEY JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY WHERE  l.L_SHIPDATE > '1996-01-01' GROUP BY l.L_SHIPMODE HAVING AVG(l.L_QUANTITY) > 25 ORDER BY avg_qty DESC;

SELECT n.N_NAME        AS nation, COUNT(c.C_CUSTKEY) AS customer_count FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY n.N_NATIONKEY, n.N_NAME HAVING COUNT(c.C_CUSTKEY) > ( SELECT AVG(cnt) FROM ( SELECT COUNT(C_CUSTKEY) AS cnt FROM   CUSTOMER GROUP BY C_NATIONKEY ) t ) ORDER BY customer_count DESC;

SELECT o.O_ORDERKEY, c.C_NAME, n.N_NAME        AS nation, r.R_NAME        AS region, o.O_TOTALPRICE FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY ORDER BY o.O_TOTALPRICE DESC LIMIT  10;

SELECT s.S_NAME, p.P_NAME, ps.PS_AVAILQTY * ps.PS_SUPPLYCOST AS stock_value FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY  = ps.PS_SUPPKEY JOIN   PART     p  ON ps.PS_PARTKEY = p.P_PARTKEY ORDER BY stock_value DESC LIMIT  20;

SELECT n.N_NAME        AS nation, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS net_revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   LINEITEM l ON o.O_ORDERKEY   = l.L_ORDERKEY GROUP BY n.N_NAME ORDER BY net_revenue DESC LIMIT  15;

SELECT c.C_CUSTKEY, c.C_NAME, n.N_NAME        AS nation, COUNT(o.O_ORDERKEY) AS order_count FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   ORDERS   o ON c.C_CUSTKEY   = o.O_CUSTKEY GROUP BY c.C_CUSTKEY, c.C_NAME, n.N_NAME ORDER BY order_count DESC LIMIT  25;

SELECT p.P_BRAND, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS    o JOIN   LINEITEM  l  ON o.O_ORDERKEY   = l.L_ORDERKEY JOIN   PART      p  ON l.L_PARTKEY    = p.P_PARTKEY JOIN   CUSTOMER  c  ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION    n  ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY  = r.R_REGIONKEY WHERE  r.R_NAME = 'EUROPE' GROUP BY p.P_BRAND ORDER BY revenue DESC LIMIT  10;

SELECT o.O_ORDERKEY, o.O_ORDERDATE, c.C_NAME, n.N_NAME        AS nation, o.O_TOTALPRICE FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY ORDER BY o.O_ORDERDATE DESC LIMIT  50;

SELECT p.P_NAME, s.S_NAME, n.N_NAME        AS nation, ps.PS_SUPPLYCOST FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY   = ps.PS_PARTKEY JOIN   SUPPLIER s  ON ps.PS_SUPPKEY = s.S_SUPPKEY JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r  ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  r.R_NAME = 'ASIA' ORDER BY ps.PS_SUPPLYCOST ASC LIMIT  15;

SELECT o.O_ORDERKEY, c.C_NAME, n.N_NAME        AS nation, AVG(l.L_DISCOUNT) AS avg_discount FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   LINEITEM l ON o.O_ORDERKEY   = l.L_ORDERKEY GROUP BY o.O_ORDERKEY, c.C_NAME, n.N_NAME ORDER BY avg_discount DESC LIMIT  20;

SELECT s.S_NAME, n.N_NAME        AS nation, AVG(ps.PS_SUPPLYCOST) AS avg_cost FROM   SUPPLIER s JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r  ON n.N_REGIONKEY = r.R_REGIONKEY JOIN   PARTSUPP ps ON s.S_SUPPKEY   = ps.PS_SUPPKEY WHERE  r.R_NAME = 'AMERICA' GROUP BY s.S_SUPPKEY, s.S_NAME, n.N_NAME ORDER BY avg_cost ASC LIMIT  10;

SELECT n.N_NAME        AS nation, YEAR(o.O_ORDERDATE) AS order_year, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   LINEITEM l ON o.O_ORDERKEY   = l.L_ORDERKEY GROUP BY n.N_NAME, YEAR(o.O_ORDERDATE) ORDER BY revenue DESC LIMIT  30;

SELECT c.C_CUSTKEY, c.C_NAME, n.N_NAME        AS nation FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  r.R_NAME = 'EUROPE' AND  EXISTS ( SELECT 1 FROM ORDERS o WHERE  o.O_CUSTKEY = c.C_CUSTKEY );

SELECT c.C_CUSTKEY, c.C_NAME, n.N_NAME        AS nation FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  r.R_NAME = 'ASIA' AND  EXISTS ( SELECT 1 FROM ORDERS o WHERE  o.O_CUSTKEY    = c.C_CUSTKEY AND  o.O_TOTALPRICE > 150000 );

SELECT s.S_SUPPKEY, s.S_NAME, n.N_NAME        AS nation FROM   SUPPLIER s JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  r.R_NAME = 'EUROPE' AND  EXISTS ( SELECT 1 FROM   PARTSUPP ps JOIN   PART     p ON ps.PS_PARTKEY = p.P_PARTKEY WHERE  ps.PS_SUPPKEY = s.S_SUPPKEY AND  p.P_SIZE      > 30 );

SELECT o.O_ORDERKEY, c.C_NAME, n.N_NAME        AS nation FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY WHERE  EXISTS ( SELECT 1 FROM LINEITEM l WHERE  l.L_ORDERKEY    = o.O_ORDERKEY AND  l.L_RECEIPTDATE > l.L_COMMITDATE );

SELECT p.P_PARTKEY, p.P_NAME FROM   PART p WHERE  p.P_PARTKEY IN ( SELECT ps.PS_PARTKEY FROM   PARTSUPP ps JOIN   SUPPLIER s ON ps.PS_SUPPKEY = s.S_SUPPKEY WHERE  s.S_ACCTBAL > 7000 ) ORDER BY p.P_NAME;

SELECT c.C_CUSTKEY, c.C_NAME, n.N_NAME        AS nation, r.R_NAME        AS region FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  NOT EXISTS ( SELECT 1 FROM ORDERS o WHERE  o.O_CUSTKEY = c.C_CUSTKEY );

SELECT DISTINCT o.O_ORDERKEY, o.O_TOTALPRICE FROM   ORDERS o WHERE  o.O_ORDERKEY IN ( SELECT l.L_ORDERKEY FROM   LINEITEM l JOIN   SUPPLIER s ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  r.R_NAME = 'EUROPE' ) ORDER BY o.O_TOTALPRICE DESC LIMIT  50;

SELECT s.S_SUPPKEY, s.S_NAME, n.N_NAME        AS nation FROM   SUPPLIER s JOIN   NATION   n ON s.S_NATIONKEY = n.N_NATIONKEY WHERE  NOT EXISTS ( SELECT 1 FROM   PARTSUPP ps WHERE  ps.PS_SUPPKEY   = s.S_SUPPKEY AND  ps.PS_SUPPLYCOST > 900 ) ORDER BY s.S_NAME;

SELECT c.C_CUSTKEY, c.C_NAME, c.C_NATIONKEY FROM   CUSTOMER c WHERE  c.C_NATIONKEY IN ( SELECT s.S_NATIONKEY FROM   SUPPLIER s GROUP BY s.S_NATIONKEY HAVING AVG(s.S_ACCTBAL) > 5000 ) ORDER BY c.C_NATIONKEY, c.C_NAME;

SELECT DISTINCT p.P_PARTKEY, p.P_NAME, p.P_BRAND FROM   PART p WHERE  p.P_PARTKEY IN ( SELECT l.L_PARTKEY FROM   LINEITEM  l JOIN   ORDERS    o  ON l.L_ORDERKEY  = o.O_ORDERKEY JOIN   CUSTOMER  c  ON o.O_CUSTKEY   = c.C_CUSTKEY JOIN   NATION    n  ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  r.R_NAME = 'AMERICA' ) ORDER BY p.P_BRAND, p.P_NAME;

SELECT DISTINCT r.R_NAME   AS region FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY WHERE  o.O_TOTALPRICE > 200000;

SELECT DISTINCT p.P_BRAND FROM   LINEITEM  l JOIN   ORDERS    o  ON l.L_ORDERKEY   = o.O_ORDERKEY JOIN   CUSTOMER  c  ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION    n  ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY  = r.R_REGIONKEY JOIN   PART      p  ON l.L_PARTKEY    = p.P_PARTKEY WHERE  r.R_NAME = 'ASIA' ORDER BY p.P_BRAND;

SELECT DISTINCT sn.N_NAME  AS supplier_nation, cn.N_NAME            AS customer_nation FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY   = c.C_CUSTKEY JOIN   NATION    cn ON c.C_NATIONKEY = cn.N_NATIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY  = l.L_ORDERKEY JOIN   SUPPLIER  s  ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION    sn ON s.S_NATIONKEY = sn.N_NATIONKEY WHERE  o.O_TOTALPRICE > 100000 ORDER BY sn.N_NAME, cn.N_NAME;

SELECT DISTINCT p.P_CONTAINER FROM   LINEITEM  l JOIN   ORDERS    o  ON l.L_ORDERKEY   = o.O_ORDERKEY JOIN   CUSTOMER  c  ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION    n  ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY  = r.R_REGIONKEY JOIN   PART      p  ON l.L_PARTKEY    = p.P_PARTKEY WHERE  r.R_NAME = 'MIDDLE EAST' ORDER BY p.P_CONTAINER;

SELECT DISTINCT c.C_MKTSEGMENT FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY WHERE  p.P_SIZE > 40 ORDER BY c.C_MKTSEGMENT;

SELECT DISTINCT r.R_NAME  AS region, p.P_BRAND FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY   = ps.PS_PARTKEY JOIN   SUPPLIER s  ON ps.PS_SUPPKEY = s.S_SUPPKEY JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r  ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  ps.PS_AVAILQTY > 500 ORDER BY r.R_NAME, p.P_BRAND;

SELECT DISTINCT l.L_SHIPMODE FROM   LINEITEM l JOIN   ORDERS   o ON l.L_ORDERKEY = o.O_ORDERKEY JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY WHERE  c.C_ACCTBAL > 8000 ORDER BY l.L_SHIPMODE;

SELECT r.R_NAME        AS region, YEAR(o.O_ORDERDATE) AS order_year, SUM(o.O_TOTALPRICE) AS revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY WHERE  o.O_ORDERDATE BETWEEN '1993-01-01' AND '1998-12-31' GROUP BY r.R_NAME, YEAR(o.O_ORDERDATE) ORDER BY r.R_NAME, order_year;

SELECT MONTH(l.L_SHIPDATE)   AS ship_month, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   LINEITEM l JOIN   ORDERS   o ON l.L_ORDERKEY = o.O_ORDERKEY JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY WHERE  YEAR(l.L_SHIPDATE) = 1996 GROUP BY MONTH(l.L_SHIPDATE) ORDER BY ship_month;

SELECT n.N_NAME        AS nation, COUNT(DISTINCT o.O_ORDERKEY) AS late_orders FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   LINEITEM l ON o.O_ORDERKEY   = l.L_ORDERKEY WHERE  l.L_RECEIPTDATE > l.L_COMMITDATE GROUP BY n.N_NAME ORDER BY late_orders DESC;

SELECT o.O_ORDERKEY, c.C_NAME, n.N_NAME        AS nation, o.O_TOTALPRICE FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY WHERE  MONTH(o.O_ORDERDATE) IN (10, 11, 12) AND  o.O_TOTALPRICE        > 100000 ORDER BY o.O_TOTALPRICE DESC LIMIT  30;

SELECT n.N_NAME        AS supplier_nation, p.P_BRAND, SUM(l.L_QUANTITY) AS total_qty FROM   LINEITEM l JOIN   PART     p  ON l.L_PARTKEY   = p.P_PARTKEY JOIN   SUPPLIER s  ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY WHERE  YEAR(l.L_SHIPDATE) = 1997 GROUP BY n.N_NAME, p.P_BRAND ORDER BY n.N_NAME, total_qty DESC;

SELECT n.N_NAME        AS nation, SUM(CASE WHEN YEAR(o.O_ORDERDATE) = 1995 THEN o.O_TOTALPRICE ELSE 0 END) AS revenue_1995, SUM(CASE WHEN YEAR(o.O_ORDERDATE) = 1996 THEN o.O_TOTALPRICE ELSE 0 END) AS revenue_1996 FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY GROUP BY n.N_NAME ORDER BY n.N_NAME;

SELECT o.O_ORDERKEY, c.C_NAME, l.L_SHIPDATE, o.O_ORDERDATE FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  DATEDIFF(l.L_SHIPDATE, o.O_ORDERDATE) <= 30 ORDER BY DATEDIFF(l.L_SHIPDATE, o.O_ORDERDATE) ASC LIMIT  50;

SELECT n.N_NAME        AS supplier_nation, AVG(DATEDIFF(l.L_RECEIPTDATE, l.L_SHIPDATE)) AS avg_transit_days FROM   LINEITEM l JOIN   SUPPLIER s  ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   ORDERS   o  ON l.L_ORDERKEY  = o.O_ORDERKEY WHERE  l.L_SHIPDATE BETWEEN '1994-01-01' AND '1997-12-31' GROUP BY n.N_NAME ORDER BY avg_transit_days ASC;

SELECT r.R_NAME        AS region, MONTH(o.O_ORDERDATE) AS peak_month, COUNT(o.O_ORDERKEY)  AS order_count FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY GROUP BY r.R_NAME, MONTH(o.O_ORDERDATE) ORDER BY r.R_NAME, order_count DESC;

SELECT r.R_NAME            AS region, YEAR(l.L_SHIPDATE)  AS ship_year, COUNT(CASE WHEN l.L_RECEIPTDATE > l.L_COMMITDATE THEN 1 END) AS late_count, COUNT(l.L_LINENUMBER) AS total_count FROM   LINEITEM l JOIN   SUPPLIER s  ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r  ON n.N_REGIONKEY = r.R_REGIONKEY GROUP BY r.R_NAME, YEAR(l.L_SHIPDATE) ORDER BY r.R_NAME, ship_year;

SELECT n.N_NAME        AS nation, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   LINEITEM l ON o.O_ORDERKEY   = l.L_ORDERKEY WHERE  c.C_ACCTBAL   > 5000 AND  o.O_ORDERDATE BETWEEN '1994-01-01' AND '1997-12-31' GROUP BY n.N_NAME HAVING SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) > 1000000 ORDER BY revenue DESC;

SELECT s.S_SUPPKEY, s.S_NAME, n.N_NAME        AS nation, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   LINEITEM  l JOIN   SUPPLIER  s  ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION    n  ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY = r.R_REGIONKEY JOIN   ORDERS    o  ON l.L_ORDERKEY  = o.O_ORDERKEY WHERE  r.R_NAME      = 'EUROPE' AND  l.L_QUANTITY  > 10 AND  l.L_SHIPDATE  > '1995-01-01' GROUP BY s.S_SUPPKEY, s.S_NAME, n.N_NAME ORDER BY revenue DESC LIMIT  15;

SELECT p.P_BRAND, p.P_TYPE, SUM(l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST) AS total_margin FROM   LINEITEM  l JOIN   PART      p  ON l.L_PARTKEY   = p.P_PARTKEY JOIN   PARTSUPP  ps ON l.L_PARTKEY   = ps.PS_PARTKEY AND l.L_SUPPKEY   = ps.PS_SUPPKEY JOIN   ORDERS    o  ON l.L_ORDERKEY  = o.O_ORDERKEY JOIN   CUSTOMER  c  ON o.O_CUSTKEY   = c.C_CUSTKEY JOIN   NATION    n  ON c.C_NATIONKEY = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  r.R_NAME = 'AMERICA' AND  p.P_SIZE > 10 GROUP BY p.P_BRAND, p.P_TYPE HAVING SUM(l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST) > 500000 ORDER BY total_margin DESC;

SELECT c.C_MKTSEGMENT, YEAR(o.O_ORDERDATE) AS yr, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue, COUNT(DISTINCT o.O_ORDERKEY)  AS order_count FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  o.O_ORDERDATE BETWEEN '1995-01-01' AND '1996-12-31' AND  l.L_DISCOUNT <= 0.06 GROUP BY c.C_MKTSEGMENT, YEAR(o.O_ORDERDATE) ORDER BY c.C_MKTSEGMENT, yr;

SELECT n.N_NAME        AS nation, SUM(CASE WHEN YEAR(o.O_ORDERDATE) = 1995 THEN l.L_EXTENDEDPRICE*(1-l.L_DISCOUNT) ELSE 0 END) AS rev_1995, SUM(CASE WHEN YEAR(o.O_ORDERDATE) = 1996 THEN l.L_EXTENDEDPRICE*(1-l.L_DISCOUNT) ELSE 0 END) AS rev_1996 FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   LINEITEM l ON o.O_ORDERKEY   = l.L_ORDERKEY GROUP BY n.N_NAME HAVING SUM(CASE WHEN YEAR(o.O_ORDERDATE) = 1996 THEN l.L_EXTENDEDPRICE*(1-l.L_DISCOUNT) ELSE 0 END) > SUM(CASE WHEN YEAR(o.O_ORDERDATE) = 1995 THEN l.L_EXTENDEDPRICE*(1-l.L_DISCOUNT) ELSE 0 END) ORDER BY n.N_NAME;

SELECT s.S_NAME, n.N_NAME        AS nation, r.R_NAME        AS region, AVG(ps.PS_SUPPLYCOST) AS avg_cost, SUM(ps.PS_AVAILQTY)   AS total_stock FROM   SUPPLIER s JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION   r  ON n.N_REGIONKEY = r.R_REGIONKEY JOIN   PARTSUPP ps ON s.S_SUPPKEY   = ps.PS_SUPPKEY WHERE  s.S_ACCTBAL > 1000 GROUP BY s.S_SUPPKEY, s.S_NAME, n.N_NAME, r.R_NAME HAVING AVG(ps.PS_SUPPLYCOST) < 400 AND SUM(ps.PS_AVAILQTY)   > 2000 ORDER BY avg_cost ASC, total_stock DESC;

SELECT p.P_BRAND, COUNT(DISTINCT r.R_REGIONKEY) AS region_count, SUM(l.L_QUANTITY)             AS total_qty FROM   LINEITEM  l JOIN   PART      p  ON l.L_PARTKEY    = p.P_PARTKEY JOIN   ORDERS    o  ON l.L_ORDERKEY   = o.O_ORDERKEY JOIN   CUSTOMER  c  ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION    n  ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY  = r.R_REGIONKEY GROUP BY p.P_BRAND HAVING COUNT(DISTINCT r.R_REGIONKEY) = 5 ORDER BY total_qty DESC;

SELECT r.R_NAME        AS supplier_region, p.P_TYPE, AVG(l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST) AS avg_margin FROM   LINEITEM  l JOIN   PART      p  ON l.L_PARTKEY   = p.P_PARTKEY JOIN   PARTSUPP  ps ON l.L_PARTKEY   = ps.PS_PARTKEY AND l.L_SUPPKEY   = ps.PS_SUPPKEY JOIN   SUPPLIER  s  ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION    n  ON s.S_NATIONKEY = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY = r.R_REGIONKEY WHERE  l.L_DISCOUNT < 0.05 GROUP BY r.R_NAME, p.P_TYPE HAVING AVG(l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST) > 1000 ORDER BY r.R_NAME, avg_margin DESC;

SELECT r.R_NAME        AS customer_region, l.L_SHIPMODE, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   ORDERS    o JOIN   CUSTOMER  c  ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION    n  ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION    r  ON n.N_REGIONKEY  = r.R_REGIONKEY JOIN   LINEITEM  l  ON o.O_ORDERKEY   = l.L_ORDERKEY WHERE  l.L_SHIPDATE BETWEEN '1995-01-01' AND '1997-12-31' GROUP BY r.R_NAME, l.L_SHIPMODE ORDER BY r.R_NAME, revenue DESC;

SELECT c.C_MKTSEGMENT, AVG(o.O_TOTALPRICE)   AS avg_order_value, COUNT(DISTINCT o.O_ORDERKEY) AS order_count FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY  = c.C_CUSTKEY JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_RECEIPTDATE <= l.L_COMMITDATE GROUP BY c.C_MKTSEGMENT HAVING AVG(o.O_TOTALPRICE) > 50000 ORDER BY avg_order_value DESC;

SELECT a.C_NAME        AS customer_a, b.C_NAME        AS customer_b, n.N_NAME        AS nation, a.C_ACCTBAL     AS balance_a, b.C_ACCTBAL     AS balance_b FROM   CUSTOMER a JOIN   CUSTOMER b  ON  a.C_NATIONKEY = b.C_NATIONKEY AND a.C_CUSTKEY   < b.C_CUSTKEY AND ABS(a.C_ACCTBAL - b.C_ACCTBAL) < 100 JOIN   NATION   n  ON  a.C_NATIONKEY = n.N_NATIONKEY ORDER BY n.N_NAME, balance_a LIMIT  30;

SELECT c.C_NAME, n.N_NAME        AS nation, o.O_ORDERKEY, CASE WHEN o.O_TOTALPRICE < 30000  THEN 'SMALL' WHEN o.O_TOTALPRICE < 100000 THEN 'MEDIUM' ELSE                              'LARGE' END             AS order_size, o.O_TOTALPRICE FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY ORDER BY o.O_TOTALPRICE DESC LIMIT  50;

SELECT r.R_NAME        AS region, SUM(CASE WHEN o.O_TOTALPRICE < 30000  THEN 1 ELSE 0 END) AS small_orders, SUM(CASE WHEN o.O_TOTALPRICE BETWEEN 30000 AND 100000 THEN 1 ELSE 0 END) AS medium_orders, SUM(CASE WHEN o.O_TOTALPRICE > 100000 THEN 1 ELSE 0 END) AS large_orders FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION   n ON c.C_NATIONKEY  = n.N_NATIONKEY JOIN   REGION   r ON n.N_REGIONKEY  = r.R_REGIONKEY GROUP BY r.R_NAME ORDER BY r.R_NAME;

SELECT s.S_SUPPKEY, s.S_NAME, n.N_NAME        AS nation, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) AS revenue FROM   LINEITEM l JOIN   SUPPLIER s  ON l.L_SUPPKEY   = s.S_SUPPKEY JOIN   NATION   n  ON s.S_NATIONKEY = n.N_NATIONKEY GROUP BY s.S_SUPPKEY, s.S_NAME, n.N_NATIONKEY, n.N_NAME HAVING SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT)) > ( SELECT AVG(nation_rev) FROM ( SELECT s2.S_NATIONKEY, SUM(l2.L_EXTENDEDPRICE * (1 - l2.L_DISCOUNT)) AS nation_rev FROM   LINEITEM  l2 JOIN   SUPPLIER  s2 ON l2.L_SUPPKEY = s2.S_SUPPKEY GROUP BY s2.S_SUPPKEY ) t WHERE t.S_NATIONKEY = s.S_NATIONKEY ) ORDER BY revenue DESC LIMIT  20;

SELECT p.P_PARTKEY, p.P_NAME, SUM(CASE WHEN YEAR(l.L_SHIPDATE) = 1995 THEN l.L_QUANTITY ELSE 0 END) AS qty_1995, SUM(CASE WHEN YEAR(l.L_SHIPDATE) = 1996 THEN l.L_QUANTITY ELSE 0 END) AS qty_1996 FROM   LINEITEM l JOIN   PART     p ON l.L_PARTKEY  = p.P_PARTKEY JOIN   ORDERS   o ON l.L_ORDERKEY = o.O_ORDERKEY GROUP BY p.P_PARTKEY, p.P_NAME HAVING SUM(CASE WHEN YEAR(l.L_SHIPDATE) = 1996 THEN l.L_QUANTITY ELSE 0 END) > SUM(CASE WHEN YEAR(l.L_SHIPDATE) = 1995 THEN l.L_QUANTITY ELSE 0 END) ORDER BY qty_1996 DESC LIMIT  20;

SELECT c.C_CUSTKEY, c.C_NAME, n.N_NAME        AS nation FROM   CUSTOMER c JOIN   NATION   n ON c.C_NATIONKEY = n.N_NATIONKEY WHERE  EXISTS (SELECT 1 FROM ORDERS o WHERE o.O_CUSTKEY = c.C_CUSTKEY AND YEAR(o.O_ORDERDATE) = 1995) AND  EXISTS (SELECT 1 FROM ORDERS o WHERE o.O_CUSTKEY = c.C_CUSTKEY AND YEAR(o.O_ORDERDATE) = 1996) ORDER BY n.N_NAME, c.C_NAME;

SELECT cr.R_NAME       AS customer_region, sr.R_NAME       AS supplier_region, COUNT(DISTINCT o.O_ORDERKEY)             AS order_count, SUM(l.L_EXTENDEDPRICE * (1-l.L_DISCOUNT)) AS gross_revenue, SUM(l.L_EXTENDEDPRICE - ps.PS_SUPPLYCOST)  AS gross_margin FROM   ORDERS    o JOIN   CUSTOMER  c   ON o.O_CUSTKEY    = c.C_CUSTKEY JOIN   NATION    cn  ON c.C_NATIONKEY  = cn.N_NATIONKEY JOIN   REGION    cr  ON cn.N_REGIONKEY = cr.R_REGIONKEY JOIN   LINEITEM  l   ON o.O_ORDERKEY   = l.L_ORDERKEY JOIN   SUPPLIER  s   ON l.L_SUPPKEY    = s.S_SUPPKEY JOIN   NATION    sn  ON s.S_NATIONKEY  = sn.N_NATIONKEY JOIN   REGION    sr  ON sn.N_REGIONKEY = sr.R_REGIONKEY JOIN   PARTSUPP  ps  ON l.L_PARTKEY    = ps.PS_PARTKEY AND l.L_SUPPKEY    = ps.PS_SUPPKEY GROUP BY cr.R_NAME, sr.R_NAME ORDER BY gross_margin DESC;