SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY;

SELECT o.O_ORDERKEY, c.C_ACCTBAL FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_ACCTBAL > 500;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE > 20000;

SELECT o.O_ORDERKEY, c.C_NATIONKEY FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_NATIONKEY BETWEEN 1 AND 10;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_ORDERDATE > '1996-01-01';

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_ACCTBAL > 100;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_ACCTBAL > 1000;

SELECT o.O_ORDERKEY, c.C_ACCTBAL FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE BETWEEN 10000 AND 30000;

SELECT o.O_ORDERKEY, c.C_NATIONKEY FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_NATIONKEY BETWEEN 5 AND 15;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_ORDERDATE BETWEEN '1995-01-01' AND '1997-01-01';

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE > 10000 AND  c.C_ACCTBAL    > 200;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE > 30000 AND  c.C_ACCTBAL    > 800;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE  BETWEEN 10000 AND 40000 AND  c.C_NATIONKEY = 5;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_ORDERDATE BETWEEN '1995-01-01' AND '1996-01-01' AND  c.C_ACCTBAL  > 1000;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_ORDERDATE   > '1996-01-01' AND  c.C_NATIONKEY BETWEEN 3 AND 8;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY > 20;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  o.O_TOTALPRICE > 30000;

SELECT o.O_ORDERKEY, l.L_SHIPDATE FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_SHIPDATE > '1996-01-01';

SELECT o.O_ORDERKEY, l.L_DISCOUNT FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_DISCOUNT > 0.05;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY > 10;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY > 30;

SELECT o.O_ORDERKEY, l.L_DISCOUNT FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_DISCOUNT BETWEEN 0.02 AND 0.08;

SELECT o.O_ORDERKEY, l.L_SHIPDATE FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_SHIPDATE BETWEEN '1995-01-01' AND '1997-01-01';

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  o.O_TOTALPRICE > 40000;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  p.P_SIZE > 10;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  ps.PS_SUPPLYCOST > 500;

SELECT p.P_PARTKEY, ps.PS_AVAILQTY FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  ps.PS_AVAILQTY > 100;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  p.P_RETAILPRICE > 1000;

SELECT s.S_SUPPKEY, ps.PS_PARTKEY FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY;

SELECT s.S_SUPPKEY, ps.PS_SUPPLYCOST FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  s.S_ACCTBAL > 500;

SELECT s.S_SUPPKEY, ps.PS_SUPPLYCOST FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  ps.PS_SUPPLYCOST > 400;

SELECT s.S_SUPPKEY, ps.PS_PARTKEY FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  s.S_NATIONKEY BETWEEN 1 AND 10;

SELECT s.S_SUPPKEY, ps.PS_AVAILQTY FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  ps.PS_AVAILQTY > 50;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_ACCTBAL    > 500 AND  o.O_TOTALPRICE > 20000;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY   > 20 AND  o.O_TOTALPRICE > 25000;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  p.P_SIZE         > 10 AND  ps.PS_SUPPLYCOST > 300;

SELECT s.S_SUPPKEY, ps.PS_SUPPLYCOST FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  s.S_ACCTBAL      > 500 AND  ps.PS_SUPPLYCOST > 300;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY ORDER BY o.O_TOTALPRICE DESC;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY ORDER BY l.L_QUANTITY DESC;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY ORDER BY c.C_ACCTBAL DESC;

SELECT o.O_ORDERKEY, l.L_DISCOUNT FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY ORDER BY l.L_DISCOUNT DESC;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY ORDER BY ps.PS_SUPPLYCOST DESC;

SELECT p.P_PARTKEY, ps.PS_AVAILQTY FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY ORDER BY ps.PS_AVAILQTY DESC;

SELECT s.S_SUPPKEY, ps.PS_SUPPLYCOST FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY ORDER BY ps.PS_SUPPLYCOST DESC;

SELECT s.S_SUPPKEY, ps.PS_AVAILQTY FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY ORDER BY ps.PS_AVAILQTY DESC;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY LIMIT  50;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY LIMIT  100;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY LIMIT  100;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY LIMIT  200;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY LIMIT  80;

SELECT s.S_SUPPKEY, ps.PS_SUPPLYCOST FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY LIMIT  60;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE > 5000;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE > 10000;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE > 15000;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE > 25000;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE > 40000;

SELECT o.O_ORDERKEY, c.C_ACCTBAL FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_ACCTBAL > 200;

SELECT o.O_ORDERKEY, c.C_ACCTBAL FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_ACCTBAL > 400;

SELECT o.O_ORDERKEY, c.C_ACCTBAL FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_ACCTBAL > 800;

SELECT o.O_ORDERKEY, c.C_ACCTBAL FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_ACCTBAL > 1200;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE > 10000 AND  c.C_ACCTBAL    > 500;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE > 20000 AND  c.C_ACCTBAL    > 700;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE > 30000 AND  c.C_ACCTBAL    > 900;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_ORDERDATE > '1994-01-01';

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_ORDERDATE > '1995-01-01';

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_ORDERDATE > '1997-01-01';

SELECT o.O_ORDERKEY, c.C_NATIONKEY FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_NATIONKEY = 1;

SELECT o.O_ORDERKEY, c.C_NATIONKEY FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_NATIONKEY = 5;

SELECT o.O_ORDERKEY, c.C_NATIONKEY FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_NATIONKEY = 10;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE BETWEEN 5000  AND 15000;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE BETWEEN 15000 AND 30000;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE BETWEEN 30000 AND 60000;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_ACCTBAL BETWEEN 200 AND 800;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_ACCTBAL BETWEEN 500 AND 1500;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS o JOIN CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE > 25000 AND  c.C_ACCTBAL  BETWEEN 200 AND 1000;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY > 5;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY > 15;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY > 25;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY > 35;

SELECT o.O_ORDERKEY, l.L_DISCOUNT FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_DISCOUNT > 0.01;

SELECT o.O_ORDERKEY, l.L_DISCOUNT FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_DISCOUNT > 0.03;

SELECT o.O_ORDERKEY, l.L_DISCOUNT FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_DISCOUNT > 0.07;

SELECT o.O_ORDERKEY, l.L_DISCOUNT FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_DISCOUNT > 0.09;

SELECT o.O_ORDERKEY, l.L_SHIPDATE FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_SHIPDATE > '1994-01-01';

SELECT o.O_ORDERKEY, l.L_SHIPDATE FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_SHIPDATE > '1995-01-01';

SELECT o.O_ORDERKEY, l.L_SHIPDATE FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_SHIPDATE > '1997-01-01';

SELECT o.O_ORDERKEY, l.L_SHIPDATE FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_SHIPDATE > '1998-01-01';

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  o.O_TOTALPRICE > 10000 AND  l.L_QUANTITY   > 10;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  o.O_TOTALPRICE > 20000 AND  l.L_QUANTITY   > 20;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  o.O_TOTALPRICE > 30000 AND  l.L_QUANTITY   > 25;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  o.O_TOTALPRICE > 40000 AND  l.L_QUANTITY   > 30;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  o.O_TOTALPRICE > 50000 AND  l.L_QUANTITY   > 35;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY BETWEEN 5  AND 15;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY BETWEEN 10 AND 20;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY BETWEEN 20 AND 40;

SELECT o.O_ORDERKEY, l.L_DISCOUNT FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY > 10 AND  l.L_DISCOUNT > 0.02;

SELECT o.O_ORDERKEY, l.L_DISCOUNT FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY > 20 AND  l.L_DISCOUNT > 0.04;

SELECT o.O_ORDERKEY, l.L_DISCOUNT FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY > 30 AND  l.L_DISCOUNT > 0.06;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  p.P_SIZE > 5;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  p.P_SIZE > 15;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  p.P_SIZE > 20;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  p.P_SIZE > 25;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  ps.PS_SUPPLYCOST > 100;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  ps.PS_SUPPLYCOST > 300;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  ps.PS_SUPPLYCOST > 700;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  ps.PS_SUPPLYCOST > 900;

SELECT p.P_PARTKEY, ps.PS_AVAILQTY FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  ps.PS_AVAILQTY > 50;

SELECT p.P_PARTKEY, ps.PS_AVAILQTY FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  ps.PS_AVAILQTY > 200;

SELECT p.P_PARTKEY, ps.PS_AVAILQTY FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  ps.PS_AVAILQTY > 300;

SELECT p.P_PARTKEY, ps.PS_AVAILQTY FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  ps.PS_AVAILQTY > 500;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  p.P_SIZE         BETWEEN 5  AND 15 AND  ps.PS_SUPPLYCOST > 200;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  p.P_SIZE         BETWEEN 15 AND 30 AND  ps.PS_SUPPLYCOST > 600;

SELECT s.S_SUPPKEY, ps.PS_PARTKEY FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  s.S_ACCTBAL > 100;

SELECT s.S_SUPPKEY, ps.PS_PARTKEY FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  s.S_ACCTBAL > 300;

SELECT s.S_SUPPKEY, ps.PS_PARTKEY FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  s.S_ACCTBAL > 600;

SELECT s.S_SUPPKEY, ps.PS_PARTKEY FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  s.S_ACCTBAL > 1000;

SELECT s.S_SUPPKEY, ps.PS_PARTKEY FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  s.S_NATIONKEY = 1;

SELECT s.S_SUPPKEY, ps.PS_PARTKEY FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  s.S_NATIONKEY = 5;

SELECT s.S_SUPPKEY, ps.PS_PARTKEY FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  s.S_NATIONKEY = 10;

SELECT s.S_SUPPKEY, ps.PS_SUPPLYCOST FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  ps.PS_SUPPLYCOST > 200;

SELECT s.S_SUPPKEY, ps.PS_SUPPLYCOST FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  ps.PS_SUPPLYCOST > 600;

SELECT s.S_SUPPKEY, ps.PS_SUPPLYCOST FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  ps.PS_SUPPLYCOST > 800;

SELECT s.S_SUPPKEY, ps.PS_PARTKEY FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  s.S_ACCTBAL      > 500 AND  ps.PS_SUPPLYCOST > 300;

SELECT s.S_SUPPKEY, ps.PS_PARTKEY FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  s.S_NATIONKEY   BETWEEN 3 AND 8 AND  ps.PS_SUPPLYCOST > 400;

SELECT s.S_SUPPKEY, ps.PS_AVAILQTY FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  ps.PS_AVAILQTY > 100;

SELECT s.S_SUPPKEY, ps.PS_AVAILQTY FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  ps.PS_AVAILQTY > 200;

SELECT o.O_ORDERKEY, l.L_DISCOUNT FROM   ORDERS o JOIN LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_DISCOUNT BETWEEN 0.02 AND 0.06;

SELECT p.P_PARTKEY, ps.PS_SUPPLYCOST FROM   PART p JOIN PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  ps.PS_SUPPLYCOST BETWEEN 200 AND 600;

SELECT s.S_SUPPKEY, ps.PS_AVAILQTY FROM   SUPPLIER s JOIN PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  ps.PS_AVAILQTY BETWEEN 50 AND 200;

SELECT o.O_ORDERKEY, c.C_NAME FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE > 20000 AND  c.C_ACCTBAL    > 500 ORDER BY o.O_TOTALPRICE DESC;

SELECT o.O_ORDERKEY, l.L_QUANTITY FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY > 20 AND  l.L_DISCOUNT > 0.03 ORDER BY l.L_QUANTITY DESC;

SELECT c.C_CUSTKEY, c.C_NAME, SUM(o.O_TOTALPRICE)   AS total_revenue FROM   CUSTOMER c JOIN   ORDERS   o ON c.C_CUSTKEY = o.O_CUSTKEY GROUP BY c.C_CUSTKEY, c.C_NAME;

SELECT c.C_CUSTKEY, c.C_NAME, AVG(o.O_TOTALPRICE)   AS avg_order_value FROM   CUSTOMER c JOIN   ORDERS   o ON c.C_CUSTKEY = o.O_CUSTKEY GROUP BY c.C_CUSTKEY, c.C_NAME;

SELECT c.C_NATIONKEY, MAX(o.O_TOTALPRICE)   AS max_order_price FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY GROUP BY c.C_NATIONKEY;

SELECT c.C_NATIONKEY, MIN(o.O_TOTALPRICE)   AS min_order_price FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY GROUP BY c.C_NATIONKEY;

SELECT c.C_NATIONKEY, COUNT(o.O_ORDERKEY)   AS order_count, SUM(o.O_TOTALPRICE)   AS total_revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_ACCTBAL > 500 GROUP BY c.C_NATIONKEY;

SELECT o.O_ORDERKEY, SUM(l.L_QUANTITY)     AS total_qty FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY o.O_ORDERKEY;

SELECT o.O_ORDERKEY, AVG(l.L_DISCOUNT)     AS avg_discount FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY o.O_ORDERKEY;

SELECT o.O_ORDERKEY, COUNT(l.L_LINENUMBER) AS line_count FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  o.O_TOTALPRICE > 20000 GROUP BY o.O_ORDERKEY;

SELECT o.O_ORDERKEY, MAX(l.L_QUANTITY)     AS max_qty, MIN(l.L_DISCOUNT)     AS min_discount FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY o.O_ORDERKEY;

SELECT YEAR(l.L_SHIPDATE)    AS ship_year, SUM(l.L_EXTENDEDPRICE) AS total_extended FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY YEAR(l.L_SHIPDATE);

SELECT p.P_SIZE, AVG(ps.PS_SUPPLYCOST) AS avg_supply_cost FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY GROUP BY p.P_SIZE;

SELECT p.P_PARTKEY, SUM(ps.PS_AVAILQTY)   AS total_availqty FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY GROUP BY p.P_PARTKEY;

SELECT p.P_TYPE, MAX(ps.PS_SUPPLYCOST) AS max_cost, MIN(ps.PS_SUPPLYCOST) AS min_cost FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY GROUP BY p.P_TYPE;

SELECT s.S_SUPPKEY, s.S_NAME, COUNT(ps.PS_PARTKEY)  AS parts_supplied FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY GROUP BY s.S_SUPPKEY, s.S_NAME;

SELECT s.S_NATIONKEY, AVG(ps.PS_SUPPLYCOST) AS avg_supply_cost FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY GROUP BY s.S_NATIONKEY;

SELECT s.S_SUPPKEY, SUM(ps.PS_AVAILQTY)   AS total_availqty FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY GROUP BY s.S_SUPPKEY;

SELECT s.S_NATIONKEY, MAX(ps.PS_SUPPLYCOST) AS max_supply_cost FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  s.S_ACCTBAL > 300 GROUP BY s.S_NATIONKEY;

SELECT c.C_CUSTKEY, COUNT(o.O_ORDERKEY)   AS order_count FROM   CUSTOMER c JOIN   ORDERS   o ON c.C_CUSTKEY = o.O_CUSTKEY WHERE  o.O_ORDERDATE > '1995-01-01' GROUP BY c.C_CUSTKEY;

SELECT o.O_ORDERKEY, COUNT(l.L_LINENUMBER) AS line_count, AVG(l.L_QUANTITY)     AS avg_qty FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_QUANTITY > 10 GROUP BY o.O_ORDERKEY;

SELECT c.C_CUSTKEY, c.C_NAME, COUNT(o.O_ORDERKEY)   AS order_count FROM   CUSTOMER c JOIN   ORDERS   o ON c.C_CUSTKEY = o.O_CUSTKEY GROUP BY c.C_CUSTKEY, c.C_NAME HAVING COUNT(o.O_ORDERKEY) > 5;

SELECT c.C_CUSTKEY, c.C_NAME, SUM(o.O_TOTALPRICE)   AS total_revenue FROM   CUSTOMER c JOIN   ORDERS   o ON c.C_CUSTKEY = o.O_CUSTKEY GROUP BY c.C_CUSTKEY, c.C_NAME HAVING SUM(o.O_TOTALPRICE) > 200000;

SELECT c.C_NATIONKEY, AVG(o.O_TOTALPRICE)   AS avg_order_value FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY GROUP BY c.C_NATIONKEY HAVING AVG(o.O_TOTALPRICE) > 30000;

SELECT o.O_ORDERKEY, COUNT(l.L_LINENUMBER) AS line_count FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY o.O_ORDERKEY HAVING COUNT(l.L_LINENUMBER) > 4;

SELECT o.O_ORDERKEY, SUM(l.L_QUANTITY)     AS total_qty FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY o.O_ORDERKEY HAVING SUM(l.L_QUANTITY) > 100;

SELECT p.P_PARTKEY, COUNT(ps.PS_SUPPKEY)  AS supplier_count FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY GROUP BY p.P_PARTKEY HAVING COUNT(ps.PS_SUPPKEY) > 2;

SELECT p.P_SIZE, AVG(ps.PS_SUPPLYCOST) AS avg_cost FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY GROUP BY p.P_SIZE HAVING AVG(ps.PS_SUPPLYCOST) > 400;

SELECT s.S_SUPPKEY, SUM(ps.PS_AVAILQTY)   AS total_qty FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY GROUP BY s.S_SUPPKEY HAVING SUM(ps.PS_AVAILQTY) > 5000;

SELECT DISTINCT c.C_CUSTKEY, c.C_NAME FROM   CUSTOMER c JOIN   ORDERS   o ON c.C_CUSTKEY = o.O_CUSTKEY;

SELECT DISTINCT c.C_NATIONKEY FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_TOTALPRICE > 50000;

SELECT DISTINCT l.L_SHIPDATE FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  o.O_TOTALPRICE > 30000;

SELECT DISTINCT p.P_TYPE FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY WHERE  ps.PS_SUPPLYCOST > 600;

SELECT DISTINCT s.S_NATIONKEY FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  ps.PS_AVAILQTY > 300;

SELECT DISTINCT o.O_ORDERKEY FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_DISCOUNT > 0.07;

SELECT o.O_ORDERKEY, c.C_NAME, o.O_TOTALPRICE FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY ORDER BY o.O_TOTALPRICE DESC LIMIT  10;

SELECT c.C_NAME, c.C_ACCTBAL, COUNT(o.O_ORDERKEY) AS order_count FROM   CUSTOMER c JOIN   ORDERS   o ON c.C_CUSTKEY = o.O_CUSTKEY GROUP BY c.C_CUSTKEY, c.C_NAME, c.C_ACCTBAL ORDER BY c.C_ACCTBAL DESC LIMIT  20;

SELECT o.O_ORDERKEY, c.C_NAME, o.O_ORDERDATE FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY ORDER BY o.O_ORDERDATE DESC LIMIT  50;

SELECT o.O_ORDERKEY, SUM(l.L_QUANTITY)    AS total_qty FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY o.O_ORDERKEY ORDER BY total_qty DESC LIMIT  10;

SELECT o.O_ORDERKEY, l.L_LINENUMBER, l.L_EXTENDEDPRICE FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_DISCOUNT > 0.04 ORDER BY l.L_EXTENDEDPRICE DESC LIMIT  25;

SELECT p.P_PARTKEY, p.P_NAME, SUM(ps.PS_AVAILQTY)  AS total_qty FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY GROUP BY p.P_PARTKEY, p.P_NAME ORDER BY total_qty DESC LIMIT  15;

SELECT s.S_SUPPKEY, s.S_NAME, AVG(ps.PS_SUPPLYCOST) AS avg_cost FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY GROUP BY s.S_SUPPKEY, s.S_NAME ORDER BY avg_cost DESC LIMIT  10;

SELECT s.S_NAME, ps.PS_PARTKEY, ps.PS_SUPPLYCOST FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY ORDER BY ps.PS_SUPPLYCOST ASC LIMIT  20;

SELECT c.C_CUSTKEY, c.C_NAME FROM   CUSTOMER c WHERE  EXISTS ( SELECT 1 FROM   ORDERS o WHERE  o.O_CUSTKEY    = c.C_CUSTKEY AND  o.O_TOTALPRICE > 100000 );

SELECT c.C_CUSTKEY, c.C_NAME FROM   CUSTOMER c WHERE  NOT EXISTS ( SELECT 1 FROM   ORDERS o WHERE  o.O_CUSTKEY  = c.C_CUSTKEY AND  o.O_ORDERDATE < '1995-01-01' );

SELECT o.O_ORDERKEY, o.O_TOTALPRICE FROM   ORDERS o WHERE  o.O_CUSTKEY IN ( SELECT c.C_CUSTKEY FROM   CUSTOMER c WHERE  c.C_NATIONKEY IN (1, 5, 10) );

SELECT o.O_ORDERKEY, o.O_TOTALPRICE FROM   ORDERS o WHERE  EXISTS ( SELECT 1 FROM   LINEITEM l WHERE  l.L_ORDERKEY = o.O_ORDERKEY AND  l.L_QUANTITY > 40 );

SELECT o.O_ORDERKEY, o.O_TOTALPRICE FROM   ORDERS o WHERE  NOT EXISTS ( SELECT 1 FROM   LINEITEM l WHERE  l.L_ORDERKEY = o.O_ORDERKEY AND  l.L_DISCOUNT > 0.0 );

SELECT p.P_PARTKEY, p.P_NAME FROM   PART p WHERE  p.P_PARTKEY IN ( SELECT ps.PS_PARTKEY FROM   PARTSUPP ps JOIN   SUPPLIER s ON ps.PS_SUPPKEY = s.S_SUPPKEY WHERE  s.S_ACCTBAL > 800 );

SELECT s.S_SUPPKEY, s.S_NAME FROM   SUPPLIER s WHERE  EXISTS ( SELECT 1 FROM   PARTSUPP ps JOIN   PART     p  ON ps.PS_PARTKEY = p.P_PARTKEY WHERE  ps.PS_SUPPKEY = s.S_SUPPKEY AND  p.P_SIZE      > 30 );

SELECT c.C_NATIONKEY, COUNT(o.O_ORDERKEY)   AS order_count, SUM(o.O_TOTALPRICE)   AS total_revenue, AVG(o.O_TOTALPRICE)   AS avg_revenue FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  o.O_ORDERDATE BETWEEN '1995-01-01' AND '1997-01-01' GROUP BY c.C_NATIONKEY ORDER BY total_revenue DESC;

SELECT c.C_NATIONKEY, YEAR(o.O_ORDERDATE)   AS order_year, COUNT(o.O_ORDERKEY)   AS order_count FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY GROUP BY c.C_NATIONKEY, YEAR(o.O_ORDERDATE) ORDER BY c.C_NATIONKEY, order_year;

SELECT YEAR(l.L_SHIPDATE)           AS ship_year, SUM(l.L_EXTENDEDPRICE * (1 - l.L_DISCOUNT))    AS net_revenue FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY YEAR(l.L_SHIPDATE) ORDER BY ship_year;

SELECT o.O_ORDERKEY, o.O_TOTALPRICE, COUNT(l.L_LINENUMBER) AS line_count FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  o.O_TOTALPRICE > (SELECT AVG(O_TOTALPRICE) FROM ORDERS) GROUP BY o.O_ORDERKEY, o.O_TOTALPRICE ORDER BY o.O_TOTALPRICE DESC LIMIT  50;

SELECT p.P_BRAND, MAX(ps.PS_SUPPLYCOST) - MIN(ps.PS_SUPPLYCOST) AS cost_spread, COUNT(ps.PS_SUPPKEY)                           AS supplier_count FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY GROUP BY p.P_BRAND ORDER BY cost_spread DESC;

SELECT s.S_SUPPKEY, s.S_NAME, COUNT(DISTINCT p.P_SIZE) AS distinct_sizes FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY  = ps.PS_SUPPKEY JOIN   PART     p  ON ps.PS_PARTKEY = p.P_PARTKEY GROUP BY s.S_SUPPKEY, s.S_NAME HAVING COUNT(DISTINCT p.P_SIZE) > 1 ORDER BY distinct_sizes DESC;

SELECT c.C_NATIONKEY, AVG(c.C_ACCTBAL)      AS avg_balance, COUNT(DISTINCT c.C_CUSTKEY) AS customer_count FROM   CUSTOMER c JOIN   ORDERS   o ON c.C_CUSTKEY = o.O_CUSTKEY GROUP BY c.C_NATIONKEY ORDER BY avg_balance DESC LIMIT  10;

SELECT YEAR(l.L_SHIPDATE)    AS ship_year, COUNT(l.L_LINENUMBER) AS discounted_lines, AVG(o.O_TOTALPRICE)   AS avg_order_price FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY WHERE  l.L_DISCOUNT > 0.06 GROUP BY YEAR(l.L_SHIPDATE) ORDER BY ship_year;

SELECT p.P_PARTKEY, p.P_NAME, SUM(ps.PS_AVAILQTY * ps.PS_SUPPLYCOST) AS stock_value FROM   PART     p JOIN   PARTSUPP ps ON p.P_PARTKEY = ps.PS_PARTKEY GROUP BY p.P_PARTKEY, p.P_NAME HAVING SUM(ps.PS_AVAILQTY * ps.PS_SUPPLYCOST) > 500000 ORDER BY stock_value DESC;

SELECT c.C_CUSTKEY, c.C_NAME, COUNT(DISTINCT o.O_ORDERSTATUS) AS status_count FROM   CUSTOMER c JOIN   ORDERS   o ON c.C_CUSTKEY = o.O_CUSTKEY GROUP BY c.C_CUSTKEY, c.C_NAME HAVING COUNT(DISTINCT o.O_ORDERSTATUS) > 1;

SELECT o.O_ORDERKEY, o.O_TOTALPRICE FROM   ORDERS o WHERE  EXISTS ( SELECT 1 FROM LINEITEM l WHERE l.L_ORDERKEY = o.O_ORDERKEY AND l.L_QUANTITY > 30 ) AND  EXISTS ( SELECT 1 FROM LINEITEM l WHERE l.L_ORDERKEY = o.O_ORDERKEY AND l.L_DISCOUNT > 0.05 );

SELECT p.P_PARTKEY, p.P_NAME FROM   PART p WHERE  p.P_PARTKEY NOT IN ( SELECT ps.PS_PARTKEY FROM   PARTSUPP ps JOIN   SUPPLIER s ON ps.PS_SUPPKEY = s.S_SUPPKEY WHERE  s.S_NATIONKEY = 5 ) LIMIT 100;

SELECT o.O_ORDERKEY, o.O_ORDERDATE, o.O_TOTALPRICE, c.C_ACCTBAL FROM   ORDERS   o JOIN   CUSTOMER c ON o.O_CUSTKEY = c.C_CUSTKEY WHERE  c.C_ACCTBAL > 1000 AND  o.O_ORDERDATE BETWEEN '1994-01-01' AND '1998-12-31' ORDER BY o.O_ORDERDATE ASC, o.O_TOTALPRICE DESC;

SELECT YEAR(l.L_SHIPDATE)    AS ship_year, MONTH(l.L_SHIPDATE)   AS ship_month, COUNT(l.L_LINENUMBER) AS total_lines, SUM(l.L_QUANTITY)     AS total_quantity FROM   ORDERS  o JOIN   LINEITEM l ON o.O_ORDERKEY = l.L_ORDERKEY GROUP BY YEAR(l.L_SHIPDATE), MONTH(l.L_SHIPDATE) ORDER BY ship_year, ship_month;

SELECT s.S_SUPPKEY, s.S_NAME, s.S_NATIONKEY, AVG(ps.PS_SUPPLYCOST) AS avg_cost, SUM(ps.PS_AVAILQTY)   AS total_stock FROM   SUPPLIER s JOIN   PARTSUPP ps ON s.S_SUPPKEY = ps.PS_SUPPKEY WHERE  s.S_ACCTBAL > 200 GROUP BY s.S_SUPPKEY, s.S_NAME, s.S_NATIONKEY HAVING AVG(ps.PS_SUPPLYCOST) < 600 AND SUM(ps.PS_AVAILQTY)   > 1000 ORDER BY avg_cost ASC LIMIT  25;